### ISSUE TITLE
Check for sister SC families

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#1740]
Add a check to make sure if the font has opentype features for small caps that there is a "family SC" family so that users can access it

Bonus points for making a pyftfeafreeze script that generates it 

Reference https://github.com/productiontype/Spectral and https://github.com/productiontype/Spectral/issues/10

**Comment by m4rc1e** [comment]
Similar to #1568

**Comment by simoncozens** [comment]
Yes, this is subsumed within #1568.
