### ISSUE TITLE
Rename `GOOGLEFONTS_SPECIFICS` in `commands/check_ufo_sources.py`

### ISSUE THREAD

**Issue by graphicore** [fonttools/fontbakery#1750]
@madig Sorry for being late to ask for this.

In [`commands/check_ufo_sources.py`](https://github.com/googlefonts/fontbakery/blob/06207a2d7aa34722b1d9e83ef6f99e23e69d9317/Lib/fontbakery/commands/check_ufo_sources.py#L12):

```py
# The values dict will probably get one or more specific blacklists
# for the google font project. It would be good if it was not necessary
# to copy paste this kind of configuration, thus a central init for
# the google/fonts repository is good.
GOOGLEFONTS_SPECIFICS = {}
```

I think calling the options variable `GOOGLEFONTS_SPECIFICS` leaves a wrong impression. This is copy and paste from [`commands/check_googlefonts.py`](https://github.com/googlefonts/fontbakery/blob/06207a2d7aa34722b1d9e83ef6f99e23e69d9317/Lib/fontbakery/commands/check_googlefonts.py#L12) Where is makes sense, because `check_googlefonts.py` is indeed meant to be specific for the "google fonts project". Maybe, we can just call it `CUSTOM_VALUES` or so in here.

Also note, the variable is unused even for google fonts, yet, it's just a possible way to inject further values.

**Comment by madig** [comment]
I'd like to see example usage of the variable.

**Comment by graphicore** [comment]
Yeah, maybe with the result of #1757 we can move hard coded data like https://github.com/madig/fontbakery/blob/81c50fb0f2af60f0645f2e3417df24fd7f83d151/Lib/fontbakery/specifications/googlefonts.py#L2025 

```py
def whitelist_camelcased_familyname(font):
  familynames = [
    "BenchNine",
    "FakeFont",
    "McLaren",
    "MedievalSharp",
    "UnifrakturCook",
    "UnifrakturMaguntia"
]
```

to the values. It would make the conditions and dependent tests better reusable.

**Comment by simoncozens** [comment]
Whatever this was is gone now.
