### ISSUE TITLE
Add checks for CFFs (and sanity check com.google.fonts/check/family_naming_recommendations)

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#1850]
In "Small general fixes" #1847 a change was made by Jens to `Lib/fontbakery/specifications/name.py` to remove this code,

    if "CFF " in ttFont:
      field = "CFF Weight"
      weight_value = ttFont["CFF "].Weight

However, I think 

- [ ] we do need a "CFF" check file that checks values in the CFF table, such as 
- [ ] a check that the CFF.Weight value matches the OS/2.usWeightClass one

This seems tricky because the existing check for weight-and-naming stuff (`com.google.fonts/check/071`) has assumptions that are not valid for TTFs (weights should be divisible by 100s to avoid smearing) but only CFFs.

- [ ] `com.google.fonts/check/071` is huge and perhaps be broken down into smaller checks that are easier to comprehend?

**Comment by simoncozens** [comment]
@davelab6 I'm going to say that we don't need this (specifically *you* don't need this ;-) since GF is TTF-centric. I suggest that instead anyone who cares about CFF checks could contribute such checks, but at any rate this is not a P0 issue.
