### ISSUE TITLE
Review GF and OT Spec check locations, to make the tool more generic

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#1945]
## Observed behaviour

While making https://github.com/googlefonts/fontbakery/pull/1944 I was surprised to find that check in the `prep.py` file; it isn't a OT spec check, but a GF specific one.

## Expected behaviour

Since we are inviting other distributors to use and contribute to this project, we should make sure that our OT spec checks are clearly separated from our GF specific ones. 

- [ ] The checks in `$table.py` files should be against the OT spec, and the checks in `googlefonts.py` should be the GF specific ones. 

- [ ] Maybe instead of a huge long `googlefonts.py` there should be `googlefonts/$table.py`?

- [ ] It should also be as easy to run fontbakery's OT Spec check set as the GF set; currently the `USAGE.md` is a bit too GF specific.

**Comment by simoncozens** [comment]
This happened in the various commits above; we also have a plan to separate googlefonts.py into smaller files, and the opentype profile works nicely with `check-opentype`.
