### ISSUE TITLE
Add specifications/cff.py

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#1991]
## Observed behaviour

There is no CFF stub for checking CFF table issues, but many upstreams offer CFF and TTF fonts, which is a kind of 'super family' check need. 

## Expected behaviour

There are a few metadata properties in the CFF table that should match the TTFs

**Comment by felipesanches** [comment]
It's been a long time since we got out first CFF checks (I think initially as part of the Adobe Fonts profile)
