### ISSUE TITLE
"Fonts have equal numbers of glyphs?" is probably a bit too simple

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#1998]
`com.google.fonts/check/011 Fonts have equal numbers of glyphs?` needs careful review...

Having a different number of glyphs can be OK between Roman and Italic, perhaps worth a warning, but there should be a fail if the Roman set and the Italic set each do not have the same glyph total, and the glyph are not named the same, and each style within each set does not have the same OT features inside.

However, what should be the same within a whole family, is the same **character support**, both their total count, and their unicode encodings. That is much more serious within the Roman/Italic sets, so should return a FAIL when all Romans or all Italics do not have the same characters, and merely WARN when Romans do not match Italics.

**Comment by madig** [comment]
The key here is to reliably separate styles (upright, italic, display, condensed, ...). This is useful in quite a few checks.

**Comment by davelab6** [comment]
> The key here is to reliably separate styles

I agree. I believe at the top of `googlefonts.py` today there are some `@condition` decorators which set up those style sets.

**Comment by madig** [comment]
This can be tricky. What if you have e.g. a display style that should be compatible with the text uprights? What if it's not compatible? Heuristics will fail one way or another. The only (reliable?) way would be to have the .designspace or source .glyphs file that specifies the instances and their masters...

**Comment by HinTak** [comment]
Ligatures are visually different between the styles. There is no reason for the Roman style to have the same numbers of ligatures as Italic?

**Comment by davelab6** [comment]
I just ran into this again.

<img width="1054" alt="screen shot 2018-11-08 at 3 32 57 pm" src="https://user-images.githubusercontent.com/261579/48233847-b0156c80-e36b-11e8-9930-00df9422028f.png">

**Comment by HinTak** [comment]
Three of the four are ligatures.

**Comment by davelab6** [comment]
Right. But my point is that the character sets (unicodes) are equal, and
glyphsets (unencoded glyphs) are not equal, and this is totally fine, as
long as within Roman and Italic sets they are all the same.

**Comment by Colophon-Foundry** [comment]
I've just come across this `FAIL` in a group of fonts we're putting together. The Italics have two stylistic sets, whereas they do not exist in the Romans. I'm currently getting a `FAIL` issue with this. Is this looking to change, or is the considered practice to put in placeholder glyphs to make the two fonts have parity?

**Comment by m4rc1e** [comment]
I wouldn't put in placeholder glyphs. This check needs refining imo.

As a temp fix, how about we just check if all fonts have the same encoded glyphs?

**Comment by felipesanches** [comment]
Adding placeholder glyphs just to make fontbakery happy would not be a good fix. It would be only gaming the system. That's why it is important for the checks to present to the user a clear description not only of the problem but also the reasoning behind it.

For instance, we should answer to the users this critical question here: `Which bad things happen when the font files in a family do not share the same set of glyphs?`

I suspect that the requirement may be related to trying to make it easier to make a variable font upgrade in the future. But I am not sure. What do you think, @davelab6 & @m4rc1e ?

**Comment by davelab6** [comment]
@felipesanches please address this as a "P0" issue, such that until it is resolved no other issues should be worked on. 

This is a P0 because it is misleading users, and it would be better to not have this test at all, than to do that.

**Comment by felipesanches** [comment]
OK!

**Comment by felipesanches** [comment]
These problematic checks are now disabled. Let's work here to fix their implementation before reintroducing them to the profile.
