### ISSUE TITLE
Check wish: validate contour directions

### ISSUE THREAD

**Issue by madig** [fonttools/fontbakery#2056]
## Expected behaviour

A check that validates all contour directions. We recently had a font-building oops that caused the cubic design outline's path direction to be preserved inside TTFs and no one noticed until it was time to check the hinting work. D'oh.

## Resources and exact process needed to replicate

Maybe FontVal knows how to do this. Might even be non-trivial/impossible to do reliably? Needs research.

**Comment by HinTak** [comment]
FontVal does indeed. See 
https://github.com/HinTak/Font-Validator/blob/master/NewHelp/E1110.htm

**Comment by madig** [comment]
The help file says that the detection might not work fully reliably. Maybe another approach would be to check only the outermost contours, since direction errors within are actually visible to the designer but invisible when *everything* is reversed. 🤔

**Comment by HinTak** [comment]
As far as I read that error message, it says if you have BOTH this and intersecting contours, you should correct the latter first, and see if this disappears also. I don't think it says it work unreliability for unknown / mystical reasons. It just says it is unreliable if you also have intersecting contour (which is another error, and you should deal with that FIRST). That's my understanding of that paragraph.

**Comment by HinTak** [comment]
Intersecting contour is E1111 . https://github.com/HinTak/Font-Validator/blob/master/NewHelp/E1111.htm

**Comment by madig** [comment]
Well, that's deal breaker for sources and e.g. variable or compatibly converted fonts.

**Comment by HinTak** [comment]
Yes, I see intersecting contours might be common with variable fonts.

**Comment by HinTak** [comment]
Had another thought. The glyf test tests rather the default instance in a variable font. It is still best practice not to have overlapping contours.

In fact I am not quite sure what is tested - it is most likely the default instance; but ideally it would be nice to do all the masters also.

**Comment by felipesanches** [comment]
thanks, @simoncozens
