### ISSUE TITLE
Test: What %age of diacritics are made Flat, with Composites, or Anchor Marks? 

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#225]
http://en.wikipedia.org/wiki/Diacritic glyphs may be made in 3 ways:
1. ø etc may be made as their own glyphs. 
2. á, í, ó, ú, ý etc may be made as 'components' with references to the base and accent glyph that exist as their own glyphs in the font
3. ắ, ặ, ế etc may be made with 'mark to mark' or 'anchor positioning' in OpenType ([explanation](http://www.glyphsapp.com/tutorials/mark-to-mark-positioning))

we should have 'note' level tests that tell us what percentage of diacritic glyphs use each of the 3 methods.

**Comment by simoncozens** [comment]
We've gone about this in a different way, because of latest GF Guide recommendations, in the `com.google.fonts/check/legacy_accents` check.
