### ISSUE TITLE
Test for kerning coverage

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#236]
- [ ] make a fontTools based script to extract flat (KERN table) kerning from a given font file 
- [ ] make a fontTools based script to extract class (GPOS table) kerning from a given font file
- [ ] make a fontTools based script to convert from flat to class based kerning
- [ ] make a fontTools based script to convert from class to flat based kerning
- [ ] make a fontTools based script to convert a given class based kern file to a refactored/idempotent class based kern file
- [ ] create a kerning (non-class, flat KERN) file from every font in the GF collection
- [ ] from that collection of flat kern files, work with @davelab6 to make a 'gf standard' kerning file for the most common kerns needed by each subset (eg in latin, common things like `AV` and `r,`)
- [ ] make a downstream test for each subset to see if it includes kerning for the 'gf standard' pairs

(This is related to https://github.com/fontforge/fontforge/issues/1895)

**Comment by madig** [comment]
> http://forum.fontlab.com/index.php?topic=8910.0 too

Hm. Wouldn't that be nice as an automatic feature in ufo2ft or so?
