### ISSUE TITLE
Add vf check for italic bug in Safari

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#2387]
## Observed behaviour

https://matthewstrom.com/writing/variable-fonts describes a safari bug where ital and slnt axes must be set correctly, or the font always renders italic. 

## Expected behaviour

We check these values are correct

**Comment by simoncozens** [comment]
We now have axis registry expectations for slant and italic, and we check our fonts against the values specified for them. If there's still an issue here, move it to axisregistry. :-)
