### ISSUE TITLE
com.google.fonts/check/repo/vf_has_static_fonts should not run on upstream repos

### ISSUE THREAD

**Issue by m4rc1e** [fonttools/fontbakery#2730]
Check com.google.fonts/check/repo/vf_has_static_fonts is running on upstream font repos. It should only run on font families that are stored in the google/fonts repo.

To replicate, run fontbakery on https://github.com/googlefonts/Inconsolata/tree/master/fonts/variable

**Comment by davelab6** [comment]
I agree. 

This came up in https://github.com/kosbarts/Commissioner/issues/13 and https://github.com/kosbarts/Commissioner/issues/14

**Comment by felipesanches** [comment]
If upstream follows the same criteria, then there will be less work to be done when preparing a PR to google/fonts. Can't we keep the requirement for upstream repos as well but improve the wording so that people understand what this is all about?

**Comment by felipesanches** [comment]
At https://github.com/kosbarts/Commissioner/issues/13#issuecomment-611597374 you said the check is "faulty" but I think that's not the case since his static font files are located at `../fonts/static` instead of the expected `./static` (its only my hunch, I have not actually verified it)

**Comment by simoncozens** [comment]
This is now correctly skipped, due to a change in the implementation of the check.
