### ISSUE TITLE
Panose monospace interpreted wrong for script, decorative and pi/dingbat fonts

### ISSUE THREAD

**Issue by tphinney** [fonttools/fontbakery#2857]
Seems like FontBakery thinks that for a font to be monospaced, the 4th digit of Panose must be 9. But that is only true IFF the first digit is 2 (Latin text).

If the first digit is either 3 (Latin Script) or 5 (Latin Picture), then the font is monospaced IFF the 4th digit is 3 (not 9! In this case the 4th digit can’t be higher than 3).

If the first digit is 4 (Latin Decorative), then no value of the 4th digit means monospaced, so there is no need to check the 4th digit at all. Or perhaps "1" for "no fit"?

See: https://monotype.github.io/panose/pan1.htm for the spec proper
Also, very handy: http://forum.high-logic.com/postedfiles/Panose.pdf

**Comment by davelab6** [comment]
@felipesanches please prioritize this and other issues @tphinney files :)

**Comment by felipesanches** [comment]
I started working on the changes needed to implement the behaviour described by @tphinney but there's still more work needed here. I'll postpone this now to our next week release.

**Comment by davelab6** [comment]
@felipesanches, as @tphinney is coming up for a release, I think you can make easy work of this :)

**Comment by tphinney** [comment]
Latest Fontbakery now throws an error for this check, on the font that caused me to file this issue.

    ERROR Failed with AttributeError: 'Panose' object has no                    
          attribute 'bSpacing'                                                  
          ↳ File "/Users/tphinney/Desktop/gmi/venv/lib/python3.9/site-packages/f
          ontbakery/checkrunner.py", line 193, in _exec_check                   
          for sub_result in result:  # Might raise.                             
          ↳ File "/Users/tphinney/Desktop/gmi/venv/lib/python3.9/site-packages/f
          ontbakery/profiles/name.py", line 184, in                             
          com_google_fonts_check_monospace                                      
          if not PANOSE_is_monospaced(ttFont['OS/2'].panose):                   
          ↳ File "/Users/tphinney/Desktop/gmi/venv/lib/python3.9/site-packages/f
          ontbakery/profiles/name.py", line 79, in PANOSE_is_monospaced         
          return panose.bSpacing == PANOSE_Spacing.MONOSPACED            

It’s a private font, but I think you have access to its repo—let me know if you need more info.

**Comment by davelab6** [comment]
@felipesanches this is a P0 for next week :)

**Comment by tphinney** [comment]
I am now using the new Fontbakery 0.8.8, which fixes the other six error messages I was recently getting (hurrah!)—but not this one.

**Comment by aaronbell** [comment]
The issue with JP fonts is a little more complex as it is due to an interaction between the xAvgCharWidth and PANOSE monospace flag (this is assuming post isFixedWidth is set to 1).

For a monospace (aka single / double width) Japanese font, the Latin characters are X width and Japanese characters are 2X width. If xAvgCharWidth is set normally (somewhere between X and 2X) then PANOSE monowidth *must not* be set or GDI will misinterpret the Japanese character widths. However if xAvgCharWidth is set “incorrectly” as X, PANOSE monowidth should be set to ensure proper rendering in GDI.

At least that’s my understanding of it!

**Comment by tphinney** [comment]
@aaronbell so if I understand you correctly 

IF you have a normal Japanese font (monospaced but with half-width Latin and full-width Japanese):

THEN, EITHER:
1) set Panose to mono and xAvgCharWidth to half-width (that is, to the Latin value, not the Japanese one and not some average between the two values)
2) set Panose to proportional and set xAvgCharWidth as you like

**Comment by tphinney** [comment]
I still get this error on Fontbakery 0.8.9

**Comment by tphinney** [comment]
I still have a Fontbakery ERROR on this every week.
It’s not a world-ender, but irksome. Here is the current way it fails (I think it changed slightly over time):

```
    ERROR Failed with AttributeError: 'Panose' object has no attribute 'bSpacing'                                                                                                            
                                                                                                                                                                                             
                                                                                                                                                                                             
            File "/usr/local/lib/python3.11/site-packages/fontbakery/checkrunner.py", line 213, in _run_check                                                                                
              subresults = list(subresults)                                                                                                                                                  
                           ^^^^^^^^^^^^^^^^                                                                                                                                                  
            File "/usr/local/lib/python3.11/site-packages/fontbakery/checks/opentype/name.py", line 223, in com_google_fonts_check_monospace                                                 
              if not PANOSE_is_monospaced(ttFont["OS/2"].panose):                                                                                                                            
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                             
            File "/usr/local/lib/python3.11/site-packages/fontbakery/checks/opentype/name.py", line 91, in PANOSE_is_monospaced                                                              
              return panose.bSpacing == PANOSE_Spacing.MONOSPACED                                                                                                                            
                     ^^^^^^^^^^^^^^^                                                                                                                                                         
                                                                                                                                                                                             
          ``` [code: failed-check]                                                                                                                                                           
                                                                                                                                                                                             

    Result: ERROR

```

**Comment by felipesanches** [comment]
> Latest Fontbakery now throws an error for this check, on the font that caused me to file this issue.
> 
> ```
> ERROR Failed with AttributeError: 'Panose' object has no                    
>       attribute 'bSpacing'                                                  
>       ↳ File "/Users/tphinney/Desktop/gmi/venv/lib/python3.9/site-packages/f
>       ontbakery/checkrunner.py", line 193, in _exec_check                   
>       for sub_result in result:  # Might raise.                             
>       ↳ File "/Users/tphinney/Desktop/gmi/venv/lib/python3.9/site-packages/f
>       ontbakery/profiles/name.py", line 184, in                             
>       com_google_fonts_check_monospace                                      
>       if not PANOSE_is_monospaced(ttFont['OS/2'].panose):                   
>       ↳ File "/Users/tphinney/Desktop/gmi/venv/lib/python3.9/site-packages/f
>       ontbakery/profiles/name.py", line 79, in PANOSE_is_monospaced         
>       return panose.bSpacing == PANOSE_Spacing.MONOSPACED            
> ```

fonttools has fixed names for panose digits, regardless of context. Here, in this snippet, we can see that digit number 4 is always called `panose.bProportion`. That's the reason why `bSpacing` is not recognized. It even doesn't exist in fonttools codebase at all!

Even though the naming is a bit misleading, it works fine. So I will fix that by using the `bProportion` name, in this case. 

![Screenshot from 2024-04-30 13-53-51](https://github.com/fonttools/fontbakery/assets/213676/b0d10d88-ea90-412e-ad5f-dce40412f842)
