### ISSUE TITLE
Carefully check that the VF instance naming tables work correctly

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#2865]
## Observed behaviour

A user wrote me,

> When I install the Quicksand fonts downloaded from fonts.google.com on windows 10 I have trouble choosing between light, regular, medium and bold, they all appear as if they were regular. 

## Expected behaviour

The fonts in github.com/google/fonts and in the ZIP downloaded from http://fonts.google.com/download?family=Quicksand should both 

- [ ] install on Windows 10 and show the styles as expected, not all as Regular

and

- [ ] pass fontbakery ot/gf profiles

I'm filing this here because I'm worried that the github fonts might not pass the latest fontbakery as they were PR'd maybe a year ago or so, or, might pass latest fontbakery and yet still not work on Windows which means the current checks are insufficient or broken.

**Comment by simoncozens** [comment]
I can't replicate this; things may have moved on. Downloaded fonts (http://fonts.google.com/download?family=Quicksand) pass all (relevant) GF checks, although there is a fail about the `font.name` in the METADATA.pb, which is about the default instance location. Style bits etc. all seem fine in the downloaded statics. I think if there was still a problem with statics being broken in Windows 10 we would hear a lot more about it...
