### ISSUE TITLE
Reduce execution time of com.google.fonts/check/varfont/generate_static

### ISSUE THREAD

**Issue by kontur** [fonttools/fontbakery#3028]
## Observed behaviour

When running fontbakery in the [Handjet repo](https://github.com/rosettatype/Handjet/commit/5338df8faf5586313d64258b52e5efaef0faf646) it seems to always get stuck at 49% after the "unitsperem" check. Incidentally, we are experiencing unresolved issues with certain glyphs from that font missing from the `GDEF` definitions — since the "gdef_mark_chars" check is the next I wonder if there is a correlation that could help both issues.

## Expected behaviour

Not get stuck. On my 2019 iMac Fontbakery seems stuck for several minutes working on that check.

## Resources and exact process needed to replicate

Checkout the [Handjet repo](https://github.com/rosettatype/Handjet/commit/5338df8faf5586313d64258b52e5efaef0faf646) and run:

```
fontbakery check-googlefonts --ghmarkdown test/Handjet-report.md fonts/Handjet\[EGRD\,ESHP\,wght\].ttf
```

**Comment by graphicore** [comment]
>  Incidentally, we are experiencing unresolved issues with certain glyphs from that font missing from the GDEF definitions — since the "gdef_mark_chars" check is the next I wonder if there is a correlation that could help both issues.

Without having looked at it yet, the TerminalReporter when used with the status bar, does some buffering before it outputs results. So, it may be very well that it stops at the gdef_mark_chars check but it did not print it yet. Use the `-n/--no-progress` flag to disable the progress bar and the buffering.

**Comment by graphicore** [comment]
It hangs for me too, right after reporting "" when I hit ctr+c to create a `KeyboardInterrupt` the traceback implies it's stuck in `com_google_fonts_check_varfont_generate_static` aka `com.google.fonts/check/varfont/generate_static`

And in fact with 
```
fontbakery check-googlefonts -x com.google.fonts/check/varfont/generate_static test/Handjet-report.md fonts/Handjet\[EGRD\,ESHP\,wght\].ttf
```
It ends for me eventually, however, not really quick either.

**Comment by kontur** [comment]
Thanks, with `-x` I can confirm it is indeed the `com.google.fonts/check/varfont/generate_static` that takes several minutes. It does end eventually, but in terms of time consumption is far beyond all others fontbakery tests (understandably, considering what it does).

In this case: There should be a better way to test if something can be done other than by actually doing it. Or rather, if the test is to do it, it should not be a test. For this font and on my iMac this single test (running with -c) takes 2:10. I'll rename the issue but keep it open, I imagine I won't be the last to wonder why this one seems to stall fontbakery.

**Comment by simoncozens** [comment]
Handjet is a bit of an outlier here. But Behdad recently worked on static instantiation in fonttools to reduce the time dramatically. See https://github.com/fonttools/fontbakery/discussions/4301#discussioncomment-7276380:

> Same PR (https://github.com/fonttools/fonttools/pull/3301) brings down instancing speed for me from 23s down to 0.36s.
