### ISSUE TITLE
error message uninformative "Generating fonts from Designspace failed: argument out of range

### ISSUE THREAD

**Issue by tphinney** [fonttools/fontbakery#3126]
I had a wrong sign on the os2.usWinDescent, but Fontbakery itself didn’t tell me that usWinDescent was the problem; only Pilcrow gave me the full detail (even though it got that info FROM Fontbakery): “invalid usWinDescent”. @simoncozens can explain in more detail.

## Observed behaviour

Error from FB was generic and non-specific

## Resources and exact process needed to replicate

(Please provide here an URL to a font file that appears to cause the issue, and the exact steps from updating to the latest code on the `master` branch to reproduce the Observed Behaviour. We need this in for replicating the issue and fixing it :)

**Comment by simoncozens** [comment]
I can't remember this. :-( I'm sorry, I'm going to close this as stale as we have no way to confirm or replicate it.
