### ISSUE TITLE
check-profile tracebacks

### ISSUE THREAD

**Issue by bobh0303** [fonttools/fontbakery#3176]
## Observed behaviour

```
fontbakery check-profile fontbakery.profiles.glyf my.ttf
```

and

```
fontbakery check-profile fontbakery.profiles.os2 my.ttf
```

both generate traceback:

```
  File "/usr/local/lib/python3.6/dist-packages/fontbakery/checkrunner.py", line 1184, in test_dependencies
    raise SetupError(f'Profile uses names that are not declared'
fontbakery.checkrunner.SetupError: Profile uses names that are not declared in its namespace: is_ttf.
```

Also:

```
fontbakery check-profile fontbakery.profiles.fvar my.ttf
```
generates a similar traceback:
```
    raise SetupError(f'Profile uses names that are not declared'
fontbakery.checkrunner.SetupError: Profile uses names that are not declared in its namespace: slnt_axis.
```

## Expected behaviour

no tracebacks expected

## Resources and exact process needed to replicate

(Please provide here an URL to a font file that appears to cause the issue, and the exact steps from updating to the latest code on the `main` branch to reproduce the Observed Behaviour. We need this in for replicating the issue and fixing it :)

I think it doesn't actually get to reading the ttf, so any font -- or no font -- will do. But if you want, try it with [Mada-Regular.ttf](https://github.com/googlefonts/fontbakery/raw/main/data/test/mada/Mada-Regular.ttf)

**Comment by simoncozens** [comment]
This seems to have been fixed somewhere along the road...
