### ISSUE TITLE
"italic" in designer's URL make fontbakery thinks the font is italic.

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#3237]
As described in https://github.com/google/fonts/pull/3275#issuecomment-815896924 : designer's url is `https://capitalics.wtf`. Since it contains italic, the check `com.google.fonts/check/metadata/canonical_style_names` thinks this is an Italic font.

**BonaNova-Bold.ttf**
🔥 FAIL: METADATA.pb: Font styles are named canonically?
com.google.fonts/check/metadata/canonical_style_names

🔥 FAIL The font style is "normal" but it should be "italic". [code: italic]

This is not an urgent matter though ;)

**Comment by felipesanches** [comment]
(sorry, I mis-typed the issue number in a commit log message. Please ignore e615c73  as it is not related to this issue)

**Comment by simoncozens** [comment]
I don't think this is true any more - I just ran the check on Bona Nova and it was fine, and I looked at the implementation of `canonical_style_names` and it seemed sensible.
