### ISSUE TITLE
Create an is_icon_font condition based on Panose values

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#3323]
@tphinney suggested: "check if the Panose declares the font to be an icon font, and default to treating it appropriately"

Some checks do not apply to icon fonts while others need to be tweaked to have slightly different checking criteria.
This Panose-based icon font detection should be placed in a condition that would be used to skip (or customize) checks so that icon fonts are inspected correctly.

**Comment by felipesanches** [comment]
I believe that such condition would default to False (not an icon font). And it could potentially be extended later with additional heuristics to detect icon fonts. I accept suggestions of other possible detection mechanisms, but we'll start with just Panose for now.

**Comment by simoncozens** [comment]
I'm working on this but I do warn you that Panose is useless. Noto Emoji has a Family Kind==5, but Noto Symbols, Noto Color Emoji and Material Symbols do not.

**Comment by tphinney** [comment]
I am sorry to hear that these Google fonts are defective!  :P
