### ISSUE TITLE
Check fvar instances are in the right order

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#3334]
Instances in the FVAR table must be in the "right" order (right is not the right word). For eg. for the weight axis: from Thin (100) to Black (900), from top to bottom. With regular progression. Not: Light (300), Thin (100), Bold (700), Regular (400), ExtraLight (200), SemiBold (600) etc..

Since we allow only weight instances in the fvar table, then we should check only the weight instances (?)

The order of instances is following the one already set in in the "exports" or "instances" tab in Glyphs, or in the "instances" section in the designspace file. So it can be fixed by reordering them there (so from source)

You can see this kind of error at this commit: https://github.com/jeremymickel/RedHatFonts/tree/645723290cb4aa843d5fb4fea68913974c334bb2/fonts/mono

This issue affects the display of instances in some dropdown menu.
This not urgent since it doesn't happen so often, but I saw it twice this week already.

**Comment by RosaWagner** [comment]
I have to add this note:

Most dropdown menus in desktop apps are displaying the weight instances automatically by taking the usWeightClass. So it is really not as severe as first indicated ;) But it does make the font checking a bit confusing, and we don't know how these fvar instances would be display in environments we are not testing. For example, Figma will be using samsa, and samsa displays the instances as they are ordered in the fvar instances (which also makes sense).

**Comment by felipesanches** [comment]
Oops! I forgot to add a changelog entry. I'll add it in a subsequent commit / PR
