### ISSUE TITLE
[Discussion] Add shaping check to gf/opentype profile?

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#3343]
## Observed behaviour

Currently if you want a shaping check, you have to ask for it in two places:

* By using `check-profile ... fontbakery.profiles.shaping`.
* By setting the `com.google.fonts/check/shaping:test_directory:` configuration option in the config file.

And obviously, since the check is in its own profile, you cannot combine the shaping check with other checks in the same fontbakery run.

## Expected behaviour

If the `com.google.fonts/check/shaping:test_directory:` configuration option is set and there are shaping check files in the appropriate directory, then the user almost certainly wants shaping check to be run. And if there is no configuration option or check files, then the shaping check can be safely skipped.

So I see no reason why this check should not be added to a more generic profile. The question is, which one is better?

**Comment by felipesanches** [comment]
yeah, let's do it!

If you crafted the shaping checks based on problems you've observed while working on QA for Google Fonts, it would make sense to, at least for now, keep it on the `googlefonts` profile, unless you're confident enough to say your checking is sufficiently generic so that we can try placing them at the `universal` profile. What do you think?

**Comment by felipesanches** [comment]
But then, would we also want to setup the GHAction settings on the google/fonts repo so that these shaping checks are executed for new family / family update PRs there, right?

It would also be good to know how much additional time would that spend on CI jobs.

**Comment by simoncozens** [comment]
I think it should go into universal!

The check is entirely driven by external, user-supplied configuration files. These files will contain shaping logic which is specific to the font, but the logic within fontbakery to drive those configuration files is completely generic.

If there are no shaping test files configured, then the shaping check is skipped; so this is a zero-cost operation when people are not using it.

**Comment by felipesanches** [comment]
perfect!

**Comment by simoncozens** [comment]
We added this to GF, which makes sense because it requires extra dependencies we didn't want to add to universal.
