### ISSUE TITLE
[wish] `com.google.fonts/check/varfont/empty_gvar`

### ISSUE THREAD

**Issue by twardoch** [fonttools/fontbakery#3401]
I’d like to request a `com.google.fonts/check/varfont/empty_gvar` check. Some toolkit (I think fontmake) may build a single-master VF that has an empty `gvar` table. 

Example font: [NotoSansLycian-VF.ttf.zip](https://github.com/googlefonts/fontbakery/files/6918918/NotoSansLycian-VF.ttf.zip) from [here](https://github.com/googlefonts/noto-fonts/raw/main/unhinted/variable-ttf/NotoSansLycian-VF.ttf)

If the font has a `glyf` table and has a completely empty `gvar` table like this: 

```
  <gvar>
    <version value="1"/>
    <reserved value="0"/>
  </gvar>
```

we should report this as a FAIL. This is a problem that does occur in real life.

**Comment by felipesanches** [comment]
It would be good if we could confirm which specific toolchain was used to build this example font.

**Comment by felipesanches** [comment]
What is the problem of an empty `gvar` table? Is it a matter of it making the filesize unnecessarily larger?

Or is it that the behavior of such a single-master VF different than an actually static font for some program or font renderer?

Does it cause the font to be broken in any manner, or is it just a minor detail?

**Comment by twardoch** [comment]
In principle, almost any table can be empty. However, I can imagine scenarios where an engine checks for the presence of gvar and then e.g. switches to a slower line layout mode (without metrics caching). I had an implementation that made a simple gvar existence check and based some logic on it. I've now added more checks. 

We still don't have a complete picture of OTVar implementations, but history tells me that software developers put various kinds of heuristics to probe font functionality. I don't think we should promote existence of font data creates ambiguity.

**Comment by felipesanches** [comment]
I understand your concern, but I'm still willing to have stronger justifications for the checks added to Font Bakery.

How would you propose wording the rationale metadata for this check? I tried to imagine how to write it but, inside my head, my inner voice still sounded too vague reading it to me.

**Comment by simoncozens** [comment]
I agree there is no good rationale for this, and in fact I can think of good reasons (color fonts) where something is a variable font but has no glyph variations. Adam, if you really want this, please feel to comment and we can reopen.
