### ISSUE TITLE
Autogenerate a lints database

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#3451]
## Observed behaviour

The Rust [clippy lints](https://rust-lang.github.io/rust-clippy/master/index.html) page is awesome.

## Expected behaviour

We should have a similar page generated from the rationales and check IDS of fontbakery checks.

**Comment by felipesanches** [comment]
Done: https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html

But it could be improved, for sure! That Rust page is indeed pretty cool. Maybe we could incorporate some aspects of that in our docs as well.

**Comment by felipesanches** [comment]
This is something that bothers me, though: #3313
