### ISSUE TITLE
CheckTester needs thinking through

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#3465]
See #3453 and #3464 for context. The situation is that we want to use `CheckTester` to run checks in a controlled and ergonomic way, but the arguments that we want to pass to `CheckTester` really depend on context and we want it to "work out" what it should do with the values we pass it:

* Sometimes we want to pass the same arguments as the underlying test function.
* Sometimes we want to pass a file name (`README.md`, or a font file name) and have that passed to the appropriate condition.
* Sometimes we want to pass a file name (`METADATA.pb`) and have that synthesise additional conditions (`font`, `fonts`).
* Often we want to pass a `ttFont` object and have it derive the remaining conditions.

Here's a good example from `adobefonts_test.py`:

https://github.com/googlefonts/fontbakery/blob/51389841fe5552b60b956b8c79a0f9eb7cd7bfb9/tests/profiles/adobefonts_test.py#L21-L30

On the first call we pass the filenames; on the second call we pass a list of `ttFont` objects.

That's a lot of magic. Good magic, perhaps, but it makes the implementation of `CheckTester` very fragile. And every time we support a new kind of file (say, `README.md`) we have to change the CheckTester class to route this file to the appropriate condition. `CheckTester` needs to have a lot of domain-specific knowledge - knowing what every object is and what to do with it. I think this is bad.

I am starting to think that the best way forward is to have `CheckTester` only handle filenames, just like the fontbakery command line. If you want to make a "bad" test file on the fly, just write it to a temp file. We should have a helper function for that. This would change e.g.:

https://github.com/googlefonts/fontbakery/blob/51389841fe5552b60b956b8c79a0f9eb7cd7bfb9/tests/profiles/dsig_test.py#L17-L25

to:

```python
    font = TEST_FILE("cabin/Cabin-Regular.ttf")
    assert_results_contain(check(font),
                           WARN, 'found-DSIG',
                           'with a font containing a DSIG table...')


    # Then we remove the DSIG table and it should now PASS the check:
	ttFont = TTFont(font)
    del ttFont['DSIG']
    assert_PASS(check(write_temp_font(ttFont)),
                'with a good font...')
```

or even:

```python
    font, ttFont = TEST_FILE("cabin/Cabin-Regular.ttf")
    assert_results_contain(check(font),
                           WARN, 'found-DSIG',
                           'with a font containing a DSIG table...')


    # Then we remove the DSIG table and it should now PASS the check:
    del ttFont['DSIG']
    assert_PASS(check(write_temp_font(ttFont)),
                'with a good font...')
```

Hardly any difference in code length and readability, but it means there doesn't need to be any magic at all in the CheckTester class.

@felipesanches, what do you think?

**Comment by felipesanches** [comment]
I think that this proposal is worse than the current state as it would unnecessarily save font files to disk.

But I agree that the current approach is still not good. The ideas below are still fresh, I have not thought much about it, so we'll have to think more carefully, but here's what I think could be done:

I've been thinking that perhaps one way to refactor this would be to annotate the assets that we pass to CheckTester. So, the `TEST_FILE` function would return an object with 2 fields: a type identifier and the actual data, which in this case would be a simple file path. We could have the same thing for any other kind of object. The "type identifier" should use the same naming of the `conditions`, so it would help in the process of dependency computation and/or injection. So, even though both `README.md` and a `font file path` and `METADATA.pb` and `DESCRIPTION.en_us.html` are all simple python strings containing a file path, they can be distinguished by this labelling mechanism, so there would be no guessing needed at all.

**Comment by simoncozens** [comment]
What’s wrong with saving font files to disk? Testing FontBakery is not a performance-critical operation. :-)

And you did want an API that mirrored the command line usage…

**Comment by felipesanches** [comment]
Well... the dict that we pass for overriding conditions is almost this. But it does not apply to the first argument we pass fo CheckTester. Maybe we could use the dict for everything, even for a simple font path or `TTFont` object. But then I dislike the idea of code-tests looking like this:  `assert_results_contain(check(ttFont=ttFont), ...`

**Comment by felipesanches** [comment]
> And you did want an API that mirrored the command line usage…

My goal is to have an API that imitates command line usage, yes. But that does not mean I want to save files unnecessarily. Or that I would want to restrict code-tests to work exclusively with file paths. On the contrary, I think the imitation is good enough if kept at the semantic level:

A user would pass a file path on the command line, but our test suite can work with a fontTools TTFont object which is more versatile while still semantically equivalent to that hypothetical user file in order to describe the test-case scenarios.

**Comment by simoncozens** [comment]
Another idea I had is for the CheckTester class to offer a few methods. One is for following the underlying function arguments, one is for purely filenames, one is for handling condition overrides etc. That way if you want cleverness you have to “pay” for it.

**Comment by felipesanches** [comment]
how would that look like?

**Comment by simoncozens** [comment]
This is now done!
