### ISSUE TITLE
(googlefonts) git repo URL should be the same in all files of the font dir

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#3521]
## Observed behaviour

We have a repo URL consistency check between OFL.txt and METADATA.pb, but not with the description and upstream.yaml. Happens regularly that I catch a different link, and it shows that the description hasn't been updated, or that the PR has been made from a a different fork. As a result we end up with multiple non-synchronised forks, and it makes any upgrade complicated.

## Expected behaviour

DESCRIPTION.en_us.html, OFL.txt, METADATA.pb and upstream.yaml should have the same git repo link.
This check is to make sure that Google Fonts user's are directed towards the actual maintained source repo of the font, where they can also find the most recent list of authors, contributors and copyright holders. This would also allow the onboarder to easily update the font from this main upstream repo by using the upstream.yaml file in the font directory.

So in a PR, it should look like this:

**upstream.yaml**
`repository_url: https://github.com/googlefonts/moondance`

**DESCRIPTION.en_us.html**
`To contribute, see <a href="https://github.com/googlefonts/moondance" target="_blank">github.com/googlefonts/moondance</a>.`

**METADATA.mb**
`copyright: "Copyright 2004 The Moon Dance Project Authors (https://github.com/googlefonts/moondance)"`

**OFL.txt**
`Copyright 2004 The Moon Dance Project Authors (https://github.com/googlefonts/moondance)`

It should be a FAIL even though it is not the most severe mistake, but re-directing users to the wrong repo is quite bad.
Obviously should be triggered only when the actual files are present.

## Where to find the error
In [this PR](https://github.com/google/fonts/pull/3988/files), the upstream.yaml doesn't have the same as OFL.txt, showing that the PR has been made from a fork 
In [this PR](https://github.com/google/fonts/pull/3989/files), the` href` has the right URL, but not the displayed text part

cc @m4rc1e @vv-monsalve for their opinion

**Comment by vv-monsalve** [comment]
Synchronized fork/repo + not being a hell for human eyes to catch it, would do this check worth. 

We have had some huge to small setbacks due to both situations.
