### ISSUE TITLE
review docs and possibly write a new "writing FB checks" section

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#3534]
I think we may only have documentation on how to write new profiles (at https://font-bakery.readthedocs.io/en/latest/developer/writing-profiles.html) but not something similar to that for the creating of new FB checks.

Docs need to be reviewed and perhaps a new section added explaining how one creates a new check.

**Comment by davelab6** [comment]
This is there, but it's a bit buried, and could be more simple to start and
with it's own section

**Comment by simoncozens** [comment]
This was done in #4545.
