### ISSUE TITLE
ERROR in com.google.fonts/check/contour_count

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#3601]
This code:

https://github.com/googlefonts/fontbakery/blob/1815d5a98e0d10873d8af3bc72568c1cc4f0c247/Lib/fontbakery/profiles/universal.py#L1310-L1311

will fail if there isn't a 3-1-0 cmap table.

**Comment by felipesanches** [comment]
can you provide a sample font file that triggers that ERROR?

**Comment by simoncozens** [comment]
No, but just change it to `ttFont.getBestCmap()`.
