### ISSUE TITLE
Should we downgrade `check/unitsperem_strict` to a WARN on Google Fonts profile?

### ISSUE THREAD

**Issue by emmamarichal** [fonttools/fontbakery#3622]
**original title of this issue was:**
FAIL: Stricter unitsPerEm criteria for Google Fonts.

## Observed behaviour

The font has 2000upm, which doesn't exactly meet the Google spec, but there are two similar checks to indicate this:
</b></summary><div><details><summary>🔥 <b>FAIL:</b> Stricter unitsPerEm criteria for Google Fonts. </summary><div>
* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)

* 🔥 **FAIL** Font em size (unitsPerEm) is 1200. If possible, please consider using 1000. Good values for unitsPerEm, though, are typically these: [16, 32, 64, 128, 256, 500, 512, 1000, 1024, 2000, 2048]. [code: bad-value]
</div></details>

</div></details><details><summary>⚠ <b>WARN:</b> Checking unitsPerEm value is reasonable.</summary><div>
* [com.google.fonts/check/unitsperem](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/head.html#com.google.fonts/check/unitsperem)

* ⚠ **WARN** In order to optimize performance on some legacy renderers, the value of unitsPerEm at the head table should idealy be a power of between 16 to 16384. And values of 1000 and 2000 are also common and may be just fine as well. But we got 1200 instead. [code: suboptimal]
</div></details>

## Expected behaviour

Chose only one fail/warn to keep.

## Resources and exact process needed to replicate

https://github.com/emmamarichal/Familjen-Grotesk/tree/master/fonts/variable

**Comment by RosaWagner** [comment]
I think the fail is too much
cc @m4rc1e @davelab6

**Comment by m4rc1e** [comment]
The check states:

> Font em size (unitsPerEm) is 1200.

This isn't a deal breaker to me.


I'd personally like to see this check dropped since it is too arbitrary. It should be up to the designer to select a upm which allows for all font details to be drawn correctly. Failing to drop it completely, it should be a warning, not a fail.

**Comment by RosaWagner** [comment]
I agree, the warn is good information though; maybe it could be INFO check?

Like: 
`UPM=1200, FYI In order to optimize performance on some legacy renderers, the value of unitsPerEm at the head table should ideally be a power of 16 between 16 to 16384.`

**Comment by felipesanches** [comment]
The reason why there are two similar checks here is because one of them is broader and comes from the universal profile, while the other one if stricter and comes from the googlefonts profile.

So, yeah, perhaps a good thing to do here would be to make the googlefonts profile remove the check inherited from universal profile.

**Comment by felipesanches** [comment]
On the PR #3798 I've just addressed the confusion by auto-skipping the OpenType one on the `googlefonts` profile.
This will be included in the upcoming v0.8.9 release.

**Comment by felipesanches** [comment]
But I will leave this issue open so that we can continue to discuss whether or not to downgrade **check/unitsperem_strict** from **FAIL** to **WARN**.

**Comment by felipesanches** [comment]
@davelab6, I'm starting to use the `"Needs Dave's opinion"` label on issues that I think you should take a look and help us decide.

In this specific case, I think I vaguely recall that making this a FAIL may have been your suggestion, as a policy to enforce good choices of UPM values for the Google Fonts collection.

Our code-tests have a long list of examples and reasoning for the choices of values deemed good or bad:
![Screenshot from 2022-06-09 07-01-23](https://user-images.githubusercontent.com/213676/172821456-db9ae666-0c49-4b26-a1e9-bb3599888cc8.png)

**Comment by simoncozens** [comment]
We've changed this in 40e78399f.
