### ISSUE TITLE
How to set check overrides per-family?

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#3623]
## Observed behaviour

In https://github.com/google/fonts/issues/3953 we have a situation where I want to make an exception to the GF profile checks for a family, in this case that the license URL metadata is valid but unusual. 

## Expected behaviour

I would like to be able to mark that exception going forwards so that for this family the check WARNs instead of FAILs. 

We've discussed ways to do this in the past, but I've lost track of if/how it can/should be done today :) 

`upstream.yml`? In the GF profile code? 

So I'm filing a new issue. 

P0!! ;p No.

**Comment by simoncozens** [comment]
We can do this by setting up a fontbakery.yml file as described here: https://github.com/fonttools/fontbakery/blob/main/docs/source/user/USAGE.md#configuration-file
