### ISSUE TITLE
Suggestion: --auto-jobs should maybe use physical core count

### ISSUE THREAD

**Issue by madig** [fonttools/fontbakery#3650]
## Observed behaviour

My CPU has hyperthreading to double the thread count, but there is no time difference between 8 and 16 threads.

## Expected behaviour

Using more threads should be faster but may fail due to synchronization or memory copying back and forth or whatever. Not using more cores than necessary could reduce waste until the code and/or Python gets better at multiprocessing.

## Resources and exact process needed to replicate

https://psutil.readthedocs.io/en/latest/index.html?highlight=cpu_count#psutil.cpu_count provides the physical core count. Not sure if easily possible without the dependency.

Maybe some people could compare times here between core counts?

**Comment by simoncozens** [comment]
I think this is going to be a not-gonna-do-it. Getting "physical" cores is OS-specific and auto-jobs is allowed to be heuristic.
