### ISSUE TITLE
[pylint] Lib/fontbakery/codetesting.py: (modified-iterating-dict)

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#3685]
![Screenshot from 2022-03-31 04-18-30](https://user-images.githubusercontent.com/213676/160999673-4584ec89-a6e2-4dcd-adba-b45341374a96.png)

https://github.com/googlefonts/fontbakery/runs/5766759335?check_suite_focus=true

**Comment by simoncozens** [comment]
This is stale.
