### ISSUE TITLE
add missing subsets to subsets menu database

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#3763]
FB report 'chinese-hongkong' is not a supported subset, but GF does display it;

🔥 FAIL: Check for METADATA subsets with zero support. ([com.google.fonts/check/metadata/unsupported_subsets](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/unsupported_subsets))
🔥 FAIL Please remove the unrecognized subset 'chinese-hongkong' from the METADATA.pb file. [code: unknown-subset]

<img width="508" alt="Capture d’écran 2022-05-04 à 17 18 29" src="https://user-images.githubusercontent.com/12222436/166714450-3cf747a9-827e-48bc-a101-0ef44df6c1f1.png">

**Comment by RosaWagner** [comment]
This is the link to the nam file into the Glyphsets module repo thing: https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/chinese-hongkong_unique-glyphs.nam in not recognise.

**Comment by RosaWagner** [comment]
Same vibe:
💔 ERROR: Check samples can be rendered. ([com.google.fonts/check/metadata/can_render_samples](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/can_render_samples))
💔 ERROR Failed with KeyError: 'cjy_Hant'

in https://github.com/google/fonts/pull/4650

**Comment by RosaWagner** [comment]
Another fail linked to this issue:

https://github.com/google/fonts/pull/4837

🔥 FAIL: Check for METADATA subsets with zero support. ([com.google.fonts/check/metadata/unsupported_subsets](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/unsupported_subsets))
🔥 FAIL Please remove the unrecognized subset 'dogra' from the METADATA.pb file. [code: unknown-subset]

cc @simoncozens @m4rc1e @vv-monsalve

**Comment by simoncozens** [comment]
I think this has been fixed by fbfbcff7.
