### ISSUE TITLE
License in name table fail even though match requirement

### ISSUE THREAD

**Issue by NightFurySL2001** [fonttools/fontbakery#3786]
>> com.google.fonts/check/name/license

    Check copyright namerecords match license file.
    with LXGWWenKai-Regular.ttf

      Rationale:
      A known licensing description must be provided in the NameID 14 (LICENSE
      DESCRIPTION) entries of the name table.

      The source of truth for this check (to determine which license is in use)
      is a file placed side-by-side to your font project including the licensing
      terms.

      Depending on the chosen license, one of the following string snippets is
      expected to be found on the NameID 13 (LICENSE DESCRIPTION) entries of the
      name table:
      - "This Font Software is licensed under the SIL Open Font License, Version
      1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL"
      - "Licensed under the Apache License, Version 2.0"
      - "Licensed under the Ubuntu Font Licence 1.0."

      Currently accepted licenses are Apache or Open Font License.
      For a small set of legacy families the Ubuntu Font License may be
      acceptable as well.

      When in doubt, please choose OFL for new font projects.

     FAIL License file LICENSE.txt exists but NameID 13 (LICENSE
          DESCRIPTION) value on platform 1 (MACINTOSH) is not specified for
          that. Value was: "This Font Software is licensed under the SIL Open
          Font License, Version 1.1. This license is available with a FAQ at:
          https://scripts.sil.org/OFL" Must be changed to "Licensed under the
          Apache License, Version 2.0" [code: wrong]

     FAIL License file LICENSE.txt exists but NameID 13 (LICENSE
          DESCRIPTION) value on platform 3 (WINDOWS) is not specified for that.
          Value was: "This Font Software is licensed under the SIL Open Font
          License, Version 1.1. This license is available with a FAQ at:
          https://scripts.sil.org/OFL" Must be changed to "Licensed under the
          Apache License, Version 2.0" [code: wrong]

    Result: FAIL

**Comment by felipesanches** [comment]
I think I can improve the wording of these check result messages to make It clearer that the problem is a mismatch of licensing declarations (name table entry versus license file contents).

I should also print out the full path of the license file.

It would also be safer to avoid the "Must be changed to" wording when talking about licences.

**Comment by felipesanches** [comment]
@NightFurySL2001, is this the repo I should use to reproduce the problem? https://github.com/lxgw/LxgwWenKai

**Comment by NightFurySL2001** [comment]
That is true, but there is 2 problem in sight:

1. It refers to License.txt when there is no License.txt when I do the check (in a separate folder, not a clone of repo).

2. The name id 13 provide in font actually matches one of the provided license statement (specifically the OFL license). This check should have been a pass.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RosaWagner** [comment]
@NightFurySL2001 What was the commit to which the issue refers? Or do you have files you can attach here for reference? Without anything thing to replicate the issue, it is not possible to fix it and therefore this issue should be closed.

**Comment by NightFurySL2001** [comment]
The version of FontBakery that report license error was at 0.8.8. I just upgraded it to 0.8.10 and it still gives the same error as the first comment.

The specific font files versions can be obtained here: https://github.com/NightFurySL2001/LxgwWenKai/tree/main/fonts/TTF

The latest font files after testing also result in the same error: https://github.com/lxgw/LxgwWenKai/tree/main/fonts/TTF

The following is the full output after I clone the latest font files from the official repo, and then run the command
`fontbakery check-googlefonts -c license .\fonts\TTF\LXGWWenKai-Regular.ttf -v`:

<details>
  <summary>Full output of FontBakery on LXGW WenKai repo with 0.8.10</summary>

```
PS D:\Desktop\font-project\LxgwWenKai> fontbakery check-googlefonts -c license .\fonts\TTF\LXGWWenKai-Regular.ttf -v
Start ... running 6 individual check executions.
 >> com.google.fonts/check/family/has_license
    Check font has a license.
    with .\fonts\TTF\LXGWWenKai-Regular.ttf


     SKIP Unfulfilled Conditions: gfonts_repo_structure


    Result: SKIP

 >> com.google.fonts/check/license/OFL_copyright
    Check license file has good copyright string.
    with .\fonts\TTF\LXGWWenKai-Regular.ttf

      Rationale:

      An OFL.txt file's first line should be the font copyright e.g: "Copyright
      2019 The Montserrat Project Authors
      (https://github.com/julietaula/montserrat)"


     FAIL First line in license file is:

          "copyright 2021 lxgw (https://github.com/lxgw/lxgwwenkai)"

          which does not match the expected format, similar to:

          "Copyright 2022 The Familyname Project Authors (git url)" [code:
          bad-format]


    Result: FAIL

 >> com.google.fonts/check/license/OFL_body_text
    Check OFL body text is correct.
    with .\fonts\TTF\LXGWWenKai-Regular.ttf

      Rationale:

      Check OFL body text is correct. Often users will accidently delete parts
      of the body text.


     SKIP Unfulfilled Conditions: is_ofl


    Result: SKIP

 >> com.google.fonts/check/name/license
    Check copyright namerecords match license file.
    with .\fonts\TTF\LXGWWenKai-Regular.ttf

      Rationale:

      A known licensing description must be provided in the NameID 14 (LICENSE
      DESCRIPTION) entries of the name table.

      The source of truth for this check (to determine which license is in use)
      is a file placed side-by-side to your font project including the
      licensing terms.

      Depending on the chosen license, one of the following string snippets is
      expected to be found on the NameID 13 (LICENSE DESCRIPTION) entries of
      the name table:

      - "This Font Software is licensed under the SIL Open Font License,
      Version 1.1. This license is available with a FAQ at:
      https://scripts.sil.org/OFL"

      - "Licensed under the Apache License, Version 2.0"

      - "Licensed under the Ubuntu Font Licence 1.0."

      Currently accepted licenses are Apache or Open Font License. For a small
      set of legacy families the Ubuntu Font License may be acceptable as well.

      When in doubt, please choose OFL for new font projects.


     FAIL License file LICENSE.txt exists but NameID 13
          (LICENSE DESCRIPTION) value on platform 1 (MACINTOSH) is not specified
          for that. Value was: "This Font Software is licensed under the SIL
          Open Font License, Version 1.1. This license is available with a FAQ
          at: https://scripts.sil.org/OFL" Must be changed to "Licensed under
          the Apache License, Version 2.0" [code: wrong]

     FAIL License file LICENSE.txt exists but NameID 13
          (LICENSE DESCRIPTION) value on platform 3 (WINDOWS) is not specified
          for that. Value was: "This Font Software is licensed under the SIL
          Open Font License, Version 1.1. This license is available with a FAQ
          at: https://scripts.sil.org/OFL" Must be changed to "Licensed under
          the Apache License, Version 2.0" [code: wrong]


    Result: FAIL

 >> com.google.fonts/check/name/license_url
    License URL matches License text on name table?
    with .\fonts\TTF\LXGWWenKai-Regular.ttf

      Rationale:

      A known license URL must be provided in the NameID 14 (LICENSE INFO URL)
      entry of the name table.

      The source of truth for this check is the licensing text found on the
      NameID 13 entry (LICENSE DESCRIPTION).

      The string snippets used for detecting licensing terms are:

      - "This Font Software is licensed under the SIL Open Font License,
      Version 1.1. This license is available with a FAQ at:
      https://scripts.sil.org/OFL"

      - "Licensed under the Apache License, Version 2.0"

      - "Licensed under the Ubuntu Font Licence 1.0."

      Currently accepted licenses are Apache or Open Font License. For a small
      set of legacy families the Ubuntu Font License may be acceptable as well.

      When in doubt, please choose OFL for new font projects.


     PASS Font has a valid license URL in NAME table.


    Result: PASS

 >> com.google.fonts/check/metadata/license
    METADATA.pb license is "APACHE2", "UFL" or "OFL"?
    with .\fonts\TTF\LXGWWenKai-Regular.ttf


     SKIP Unfulfilled Conditions: family_metadata


    Result: SKIP


Total:

    ERROR: 0
    FAIL: 2
    WARN: 0
    INFO: 0
    SKIP: 3
    PASS: 1

[SFSFPS] 100%

DONE!

    Meaning of check results:

    An ERROR is something wrong with FontBakery itself, possibly a bug.
    A FAIL is a problem with the font that must be fixed.
    A WARN is something that you should consider addressing.
    An INFO result simply prints something useful. Typically stats.
    A PASS means the font looks good for the given checking routine.
    And a SKIP happens when the check does not apply to the given font.

    If you get ERRORs, please help us improve the tool by reporting them at
    https://github.com/googlefonts/fontbakery/issues

    (but other kinds of bug reports and/or
     feature requests are also always welcome, of course!)
```

</details>

**Comment by RosaWagner** [comment]
GF has very strict license requirements. 
- You can't use 2 copyright strings, and the one you use needs to follow the given scheme.
- You need to use the same OFL template as GF use in every other projects (https://github.com/googlefonts/googlefonts-project-template/blob/main/OFL.txt). This is the only way we can be sure the license has not been manually altered in some part. 
- If you are using a OFL license, then the license file needs to be OFL.txt, 'License.txt' is expected for Apache license. Once that corrected, it should stop FAIL about the license string in font file not being adéquate.
- It is recommended to use httpS urls, and to have everything consistent (even the httpS) between the font file and the license file.

This is of course if you intend your font for Google Fonts.

So I would say that these checks are actually correct, if they FAIL or WARN it means there is a good chance that there is something "wrong" (for GF) about your copyright and license string. We could improve the wording to make it clearer maybe. This is the related chapter in the guide: https://googlefonts.github.io/gf-guide/license-file.html

**Comment by RosaWagner** [comment]
@NightFurySL2001 Don't forget to add AUTHORS.txt file so your license file makes sense when mentioning the font's "project authors" (https://googlefonts.github.io/gf-guide/authors.html)

**Comment by NightFurySL2001** [comment]
I see, thank you. The problem is with the license file name. It seems weird to enforce the use of "OFL.txt" as the filename in check, but I guess it is what is it.

The guide could be updated to be more clearer.
