### ISSUE TITLE
skip [com.google.fonts/check/version_bump] when PR doesn't contain font.

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#3830]
Found in https://github.com/google/fonts/pull/4964
This PR only contains a description file. Imo this check should be skipped when there is no font in the PR.

```
🔥 FAIL: Version number has increased since previous release on Google Fonts? ([com.google.fonts/check/version_bump](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/version_bump))
🔥 FAIL Version number 1.0 is equal to version on Google Fonts.
🔥 FAIL Version number 1.0 is equal to version on Google Fonts GitHub repo.
```

**Comment by RosaWagner** [comment]
I have the feeling this has been implemented cause no FAIL on version string in this PR: https://github.com/google/fonts/pull/5482

@felipesanches do you remember fixing it?

**Comment by felipesanches** [comment]
I haven't done it. But perhaps someone updated the google/fonts CI rules to skip the check in that scenario? I don't know.

**Comment by simoncozens** [comment]
Yes, this has happened at the level of `.ci/run.py` inside the GF repo, which determines which checks need to be run for which files.
