### ISSUE TITLE
Bad markdown in 0.8.9?

### ISSUE THREAD

**Issue by koeberlin** [fonttools/fontbakery#3862]
Hi, 
I just updated fontbakery to 0.8.9 on a new machine, and it looks like the markdown got messed up?

<img width="1416" alt="Bildschirmfoto 2022-08-17 um 14 01 12" src="https://user-images.githubusercontent.com/93979655/185114245-3b055612-1681-4621-bdc9-8a05dde88ead.png">

The report was created with the following code:
`fontbakery check-universal *[ot]tf --loglevel WARN --ghmarkdown fontbakery_report.md`

Above: MacOS 10.14.6, fontbakery 0.8.1
Below: MacOS 12.5, fontbakery 0.8.9

Any ideas?

Thank you!
Christoph

**Comment by felipesanches** [comment]
Thanks for reporting this. I will try to replicate the problem here.

**Comment by felipesanches** [comment]
There's a Markdown glitch here as well: https://github.com/google/fonts/pull/4988#issuecomment-1196780759 (Summary header does not render. It is simply shown as `### Summary` instead).

**Comment by vv-monsalve** [comment]
Similar issues under FB v0.8.10 

- The list of reported Fails is displayed directly now and not contained under a collapsable dropdown per font
<img width="1772" alt="Screen Shot 2022-10-12 at 19 51 38" src="https://user-images.githubusercontent.com/48698976/195474572-98c87d8c-8bab-4e9e-b826-7bdbeaa86611.png">

----

- The new tables included in some checks reports are broken in MacDown

<img width="856" alt="Screen Shot 2022-10-12 at 19 57 58" src="https://user-images.githubusercontent.com/48698976/195474713-e648df09-5b56-4957-b66d-368bf5baa6c1.png">

**Comment by simoncozens** [comment]
This is now fixed, apart from #3982.

**Comment by felipesanches** [comment]
This was fixed by PR #3923 `"Fix summary header in the Github Markdown reporter."` and released on 0.8.11
