### ISSUE TITLE
com.google.fonts/check/family/panose_proportion: can a Family contain Width variations?

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fontbakery#3867]
## Observed behaviour

I'm running the check-universal profile on a static family that contains both Condensed and non-Condensed fonts, and the PANOSE proportion values reflect this. I'm getting this FAIL:

<Section: fontbakery.profiles.os2> 🔥
Fonts have consistent PANOSE proportion?
Check ID: <FontBakeryCheck:com.google.fonts/check/family/panose_proportion>
🔥 Family check
🔥 FAIL
PANOSE proportion is not the same across this family. In order to fix this, please make sure that the panose.bProportion value is the same in the OS/2 table of all of this family font files. [code: inconsistency]

## Expected behaviour

The PANOSE proportion values within the family are expected to be different for Condensed and non-Condensed, so this appears to be a false positive in our case.

**Comment by punchcutter** [comment]
Same problem here on multiple families that have widths like Condensed, Semicondensed, Normal, Extended

**Comment by simoncozens** [comment]
Duplicate -> #4083. I think this check needs to be removed.
