### ISSUE TITLE
Different emojis in between markdown summary and html report

### ISSUE THREAD

**Issue by guidoferreyra** [fonttools/fontbakery#3890]
## Observed behaviour

The used emojis are different in between markdown summary and html report.

| Status | html | markdown |
|--------|------|----------|
| Warn*   | ⚠️    | ⚠        |
| Pass   | ✅    | 🍞        |
| Skip   | ⏩    | 💤        |
| Error  | 💥    | 💔        |
| Info*   | ℹ️    | ℹ        |

*⚠️ and ℹ️ render the same here on github but the characters are different.

## Expected behaviour

Maybe use the current emojis from html in the markdown

**Comment by felipesanches** [comment]
Does this affect some system? Or is it a proposal for a merely aesthetical tweak?

**Comment by guidoferreyra** [comment]
Is kind of aesthetical but at the same time IMO consistency is good, it helps to navigate faster reports

Here an image where the difference is more visible.
![imagen](https://user-images.githubusercontent.com/1755590/190542897-d442afc5-0950-4d0f-9bdc-4a612bef4734.png)

**Comment by simoncozens** [comment]
Fixed in #4559 .
