### ISSUE TITLE
What is the rationale for [transformed components FAIL] if a font is not hinted with ttfa?

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#3966]
> What is the rationale for this fail *if a font is not hinted with ttfa*?
> It looks like this landed in universal and we are now failing on unhinted TT font builds.

_Originally posted by @chrissimpkins in https://github.com/googlefonts/fontbakery/issues/2011#issuecomment-1051084068_

**Comment by simoncozens** [comment]
Merging with #4024.
