### ISSUE TITLE
[com.google.fonts/check/outline_colinear_vectors] HTML code of MD file is faulty

### ISSUE THREAD

**Issue by yanone** [fonttools/fontbakery#3982]
Link in `<a>` tags contains `<Section: Outline Correctness Checks>` (several instances) which leads to faulty HTML and confusing output as can be seen in below screenshot.

The MD file is attached below. The command was run as `fontbakery check-googlefonts -j -F -l WARN Braah.ttf --ghmarkdown ~/Desktop/qa_braah/md.md` on https://github.com/ashishdes/Braah/blob/main/Braah.ttf

<img width="1792" alt="Bildschirmfoto 2022-12-06 um 11 15 41" src="https://user-images.githubusercontent.com/175386/205883879-ee4aec5c-7b17-4453-a48a-e58b46373351.png">

[md.md](https://github.com/googlefonts/fontbakery/files/10165095/md.md)

**Comment by simoncozens** [comment]
This has been fixed!
