### ISSUE TITLE
[com.google.fonts/check/transformed_components] Should not have is_hinted as condition?

### ISSUE THREAD

**Issue by guidoferreyra** [fonttools/fontbakery#4024]
## Observed behaviour

This check is performed over all ttf files but according to the know issue and the [rationale](https://github.com/googlefonts/fontbakery/blob/e0c32fbeb470a141c744f1197bcef0c66e6a993e/Lib/fontbakery/profiles/universal.py#L1588) it should not only be ran over hinted files? For instance VFs are commonly not hinted.

## Expected behaviour

Ignore not hinted VFs

**Comment by simoncozens** [comment]
This is a duplicate of #3738
