### ISSUE TITLE
[com.google.fonts/check/hmtx/whitespace_advances] U+2003 EM SPACE need not match `unitsPerEm`

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fontbakery#4079]
## Observed behavior

`com.google.fonts/check/hmtx/whitespace_advances` requires the widths of certain space characters like U+2003 EM SPACE to be multiples of the font’s `unitsPerEm`.

## Expected behavior

Those space characters should be defined in terms of the width of U+2003. `unitsPerEm` is a font-internal implementation detail that needn’t correspond to anything user-visible.

**Comment by simoncozens** [comment]
This check is just for the Noto profile. While what you say is true in general, I think it *was* (at least at some point) a requirement for Noto project fonts, so I think it's fine to be on that particular profile.
