### ISSUE TITLE
[com.google.fonts/check/valid_glyphnames] Outdated URL in rationale

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fontbakery#4080]
## Observed behavior

`com.google.fonts/check/valid_glyphnames` has the rationale:

https://github.com/fonttools/fontbakery/blob/97facb7b32846ce8fb8b810af0e7f78de8e0fe4f/Lib/fontbakery/profiles/universal.py#L1098-L1106

The page at that URL no longer includes the quoted text.

## Expected behavior

The check’s rationale explains the 31-character glyph limit in the context of the AGL specification (which is currently mentioned later in the rationale) because the AGL specification still mentions that limit.

**Comment by miguelsousa** [comment]
The [oldest archived version of that page](https://learn.microsoft.com/en-us/typography/opentype/otspec140/recom#post-table) (OpenType version 1.4, originally published in 2007) doesn't have that note either.

**Comment by felipesanches** [comment]
Today I can see the quote in here: https://learn.microsoft.com/en-us/typography/opentype/otspec181/recom

**Comment by felipesanches** [comment]
More precisely here: https://learn.microsoft.com/en-us/typography/opentype/otspec181/recom#-post--table
