### ISSUE TITLE
[com.google.fonts/check/family/panose_proportion] wants panose.bProportion to be the same without rational

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fontbakery#4083]
## Observed behaviour

A family with condensed styles sets the panose.bProportion of the condensed style to 6, and sets it to 2 for the rest, but this check FAIL’s on such a family.

## Expected behaviour

No FAIL since panose.bProportion is set to the correct value.

## Resources and exact process needed to replicate

I can’t share the affected fonts.

**Comment by felipesanches** [comment]
I feel less inclined to attempt addressing the problem without a font file that replicates the problem.

Can someone craft an example font that can be shared?

**Comment by khaledhosny** [comment]
It is easy to make test fonts, but there is zero rational given for the check (and it is a FAIL not even a WARN), so I don’t know how to asses whether the fonts are correct or not. I don’t even know what PANOSE is used for to warrant a FAIL for some obscure font info field.

**Comment by simoncozens** [comment]
Yeah, I think the fix is to deprecate the check here.
