### ISSUE TITLE
deprecate [com.google.fonts/check/repo/vf_has_static_fonts]

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#4092]
⚠ WARN: A static fonts directory with at least two fonts must accompany variable fonts ([com.google.fonts/check/repo/vf_has_static_fonts](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/vf_has_static_fonts))
⚠ WARN Please consider adding a subdirectory called "static/" and including in it static font files. [code: missing]

The only case where we need the `static` folder is when teh statics are manually hinted, which almost never occurs. Maybe the check could instead warn to remove the fonts in the static folder if they are not manually hinted.

cc @m4rc1e @vv-monsalve @yanone thumbs up if you agree.

**Comment by vv-monsalve** [comment]
> Maybe the check could instead warn to remove the fonts in the static folder if they are not manually hinted.

Agree. We haven't used/required this dir in a while.
