### ISSUE TITLE
[com.google.fonts/check/mandatory_glyphs] empty .notdef upgrade to FAIL

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#4093]
⚠ WARN: Font contains '.notdef' as its first glyph? ([com.google.fonts/check/mandatory_glyphs](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/mandatory_glyphs))
⚠ WARN Glyph '.notdef' should contain a drawing, but it is empty. [code: empty]

Empty .notdef can be confusing for users to have a space instead of a missing glyph, and it makes harder on our side to spot tofu on the specimen page and therefore to fix the font. A missing glyph should be "obviously" missing, therefore I propose googlefonts profile to make it a requirement. The warn will be then less ignored (I am trying to reduce the list of ignored warn here).

Tip: if .notdef is not in sources, ufo2ft will create it with proper box outline. So you would only need to remove it from the sources to not fail the check.

cc @m4rc1e @vv-monsalve @yanone thumbs up if you agree.

**Comment by yanone** [comment]
I would make this a FAIL

**Comment by felipesanches** [comment]
I agree as well.

**Comment by yanone** [comment]
Actually: FAIL for GF, otherwise WARN. Other foundries need to decide this themselves.

**Comment by felipesanches** [comment]
yes, indeed!

**Comment by khaledhosny** [comment]
FWIW, some applications never show the font’s `.notdef` glyph. For example Firefox and Pango will show a hex box containing the hex value of the code point if no other font supports the character.

**Comment by vv-monsalve** [comment]
> Actually: FAIL for GF, otherwise WARN. Other foundries need to decide this themselves.

It should Fail everywhere since `.notdef` shouldn't be empty according to the [Spec](https://learn.microsoft.com/en-us/typography/opentype/otspec183/recom#glyph-0-the-notdef-glyph).

> The .notdef glyph is very important for providing the user feedback that a glyph is not found in the font. This glyph should not be left without an outline as the user will only see what looks like a space if a glyph is missing and not be aware of the active font’s limitation.
