### ISSUE TITLE
[com.google.fonts/check/unitsperem_strict] should be deprecated or improved

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#4094]
## Observed behaviour
🔥 FAIL: Stricter unitsPerEm criteria for Google Fonts. ([com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict))
🔥 FAIL Font em size (unitsPerEm) is 1240. If possible, please consider using 1000. Good values for unitsPerEm, though, are typically these: [16, 32, 64, 128, 256, 500, 512, 1000, 1024, 2000, 2048]. [code: bad-value]

## Expected behaviour

Per spec, authorized range is 16 to 16384. So this check should only FAIL on universal profile if the UPM is out of that range.
cf https://learn.microsoft.com/en-us/typography/opentype/spec/head. Same for Google Fonts profile, we actually haven't care about the UPM size for 2-3 years now.

Otherwise people do whatever they want, maybe we could WARN if UPM is bigger than 4000 for performance issues on older machines? but even that I am not so sure, it would need proper proof. But it would be the opportunity to give the already given advise "If possible, please consider using 1000 or 2000. Good values for unitsPerEm, though, are typically these: [16, 32, 64, 128, 256, 500, 512, 1000, 1024, 2000, 2048]."

## Resources and exact process needed to replicate
Seen in https://github.com/google/fonts/pull/6026#issuecomment-1470185487

**Comment by felipesanches** [comment]
The UPM check has gradually evolved based on feedback and requests by @davelab6 and others.
Please see the code-test which includes explanation of all criteria:
![Screenshot from 2023-03-16 12-11-28](https://user-images.githubusercontent.com/213676/225613541-4a646921-5e50-4ee2-917b-81a0e5752a82.png)
