### ISSUE TITLE
[com.google.fonts/check/name/family_and_style_max_length] Please don't count 'Regular'

### ISSUE THREAD

**Issue by moontypespace** [fonttools/fontbakery#4104]
## Observed behaviour
Quite often I have the situation that this check gives me a warning that a name exceeds the limitation of 27 characters. And I much appreciate this test, because it's super handy and very important. BUT my personal experience is, that if the subfamily name is 'Regular', 'Regular' can be ignored in the character count.

Here is an example:
FONT_FAMILY_NAME = 'Name Micro ExtraBlack' / SUBFAMILY_NAME = 'Regular' => exceeds 27 characters.
BUT if the SUBFAMILY_NAME equals 'Regular', I would count only the character of the FONT_FAMILY_NAME.
In that example it would pass the test, because  'Name Micro ExtraBlack'  has 21 characters and does not exceed the limitation of 27.

## Expected behaviour
Ignore SUBFAMILY_NAME if SUBFAMILY_NAME == 'Regular'.

## Resources and exact process needed to replicate
Sadly no resources, just my own experiences over the years. Sorry.
BTW: My character limitation for the whole font name is 31 (without 'Regular'). But I know, that there are many other experiences related to this discussion.

**Comment by felipesanches** [comment]
I'm curious to learn about your methods to come up with this conclusion, because I would like to replicate your method independently, or maybe ask others to do so for me.

What is your way of deciding whether these are reasonable criteria or not? Do you know which programs do not handle well longer names and then you can notice that "Regular" does not affect the results of such experiments? If so, which are these programs?

**Comment by moontypespace** [comment]
I work with the limitation 31 characters (without 'Regular') for the full name, which means name table 1+2, 4, 16+17, 21+22 should not exceed 31 characters.

Name ID 1 = 'Some Sans Condensed ExtraLight'
Name ID 2 = 'Regular'
Name ID 4 = 'Some Sans Condensed ExtraLight'
Name ID 6 = 'SomeSansCondensed-ExtraLight'
Name ID 16 = 'Some Sans Condensed'
Name ID 17 = 'ExtraLight'

1+2(if not 'Regular) = 'Some Sans Condensed ExtraLight' => Pass because 30 characters
4 = 'Some Sans Condensed ExtraLight' => Pass because 30 characters
16+17 = 'Some Sans Condensed ExtraLight' => Pass because 30 characters

Name ID 1 = 'Some Sans Condensed ExtraLight'
Name ID 2 = 'Italic'
Name ID 4 = 'Some Sans Condensed ExtraLight Italic'
Name ID 6 = 'SomeSansCondensed-ExtraLightItalic'
Name ID 16 = 'Some Sans Condensed'
Name ID 17 = 'ExtraLight Italic'

1+2(if not 'Regular) = 'Some Sans Condensed ExtraLight Italic' => Error because 37 characters
4 = 'Some Sans Condensed ExtraLight Italic' => Error because 37 characters
16+17 = 'Some Sans Condensed ExtraLight Italic' => Error because 37 characters

I don't care too much about name table ID 6, because usually all spaces get replaced anyway. So, when the other name table entries do not exceed the limitation of 31, name table ID 6 should be fine.

Does that make sense to you?

And about your app question: So, my experience is that in most cases it's related to MS Office (MS Word).

**Comment by moontypespace** [comment]
I often read over this message on purpose. And I assume a lot of other people do, too. But it could be such a useful check if it took into account what @RosaWagner  and I mentioned.
