### ISSUE TITLE
[com.adobe.fonts/check/varfont/same_size_instance_records] fails when no instance records are present

### ISSUE THREAD

**Issue by mekkablue** [fonttools/fontbakery#4105]
## Observed behaviour

An OTVAR without instance records in fvar makes the check FAIL.

## Expected behaviour

fvar can be without instance records according to https://learn.microsoft.com/en-us/typography/opentype/spec/fvar#instancerecord (scroll to the note at the end), and this check should at most return WARN or (preferably) SKIP in such cases.

## Resources and exact process needed to replicate

[test_no_instance_records.ttf.zip](https://github.com/googlefonts/fontbakery/files/11055118/test_no_instance_records.ttf.zip)

**Comment by simoncozens** [comment]
At some point this was fixed, we now get:

```
    SKIP Font has no instance records. [code: no-instance-records]
```
