### ISSUE TITLE
deprecate [com.google.fonts/check/fontv]

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#4138]
(**NOTE:** Please include the check-id on the issue title. Check-id example [com.google.fonts/check/metadata/parses])

## Observed behaviour

ℹ INFO: Check for font-v versioning. ([com.google.fonts/check/fontv](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fontv))
ℹ INFO Version string is: "Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.29]"
The version string must ideally include a git commit hash and either a "dev" or a "release" suffix such as in the example below:
"Version 1.3; git-0d08353-release" [code: bad-format]

## Expected behaviour

This doesn't match our current requirements for font versioning and I don't see the point in having it as an INFO check. We have a FAIL in case the version is not following the guidelines.

**Comment by davelab6** [comment]
@RosaWagner thanks for posting this. Fair question! :)

@chrissimpkins I guess we added this as an info check to recommend people follow the versioning you designed in fontv. Do you think it's worth upping the importance of this version style?

**Comment by chrissimpkins** [comment]
Ok by me

**Comment by felipesanches** [comment]
* OK to make it a WARN, as suggested by Dave?
* Or to deprecate it, as suggested by Rosalie?

**Comment by chrissimpkins** [comment]
Oh apologies.  I was reading this as deprecating it.  @davelab6 do you want to keep this syntax for version strings?

**Comment by chrissimpkins** [comment]
I discussed it with Dave.  Let's remove font-v and its fixed syntax and keep the Fonts nameID 5 syntax that includes the git commit sha.
