### ISSUE TITLE
New check: glyphs mapping consistent between Roman/italic

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#4180]
## What needs to be checked?

We had the case for Rubik Arabic where arabic was in the upright style but not the Italic. We don't want an arabic italic style but we do want the same number of encoded glyphs in each style. 

## Detailed description of the problem 

Missing encoded glyphs in a linked Italic styles would produce fake italic (or tofu) in some apps for these glyphs only, while the other ones would display correctly.

## Optional fix

The missing glyphs could be simply designed; but in some case it might be wanted that certain glyphs remain upright in the italic style (some math glyphs, or world scripts which are not usually slanted for text enhancement). In that case the missing glyphs should be be imported in the Italic style from the upright.

## Resources and exact process needed to replicate

Rubik at that commit: https://github.com/googlefonts/rubik/commit/9167c98fa8699d75ee51769eba20d81beb16bcb5

## Expected Profile

Please suggest in which profile should it be included. (You could inspect the Profiles's list at https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/index.html). Most common are:

- [x] Vendor-specific: Google Fonts
- [ ] Vendor-specific: Adobe Fonts
- [ ] OpenType (requirements imposed by the OpenType specification)
- [ ] Universal (broadly accepted best practices on the type design community)
- [ ] Other:

## Expected Result

Which log result level should it have:

- [x] 🔥 **FAIL** (Something that must be addressed for the proper functioning of the font)
- [ ] ⚠️ **WARN** (Highlights potential issues that are suggested to address)

## Severity assessment

4 

(On a 1 to 5 level, how "buggy" would the font be considered if not including the aspect checked? Where 1 is something ideal to include but that would not affect the behavior of the font, and 5 is something that could lead to bad performance.)

**Comment by simoncozens** [comment]
This is actually the same as #1998, but this issue is better so I'm closing the other one.
