### ISSUE TITLE
Weird display in cmd/PowerShell

### ISSUE THREAD

**Issue by domija** [fonttools/fontbakery#4189]
Hi,

**Describe the issue**
After reinstalling Python 3.10.10 (Windows 10) and downloading font bakery by running the "pip install fontbakery" command, when I run fontbakery check, part of the text preview in the cmd/PowerShell is not displaying correctly. Output to .json works fine.

**To Reproduce**
See above.

**Suggested behavior**
Display characters correctly. Before reinstalling, it used to work just fine.

**Additional context**
Windows 10, 64bit.

**Screenshots**
![obrazek](https://github.com/googlefonts/fontbakery/assets/36168990/61e32a19-f1c7-4073-a193-97e08e10d2d0)

**Comment by graphicore** [comment]
Hi @domija, the weird characters are [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) used to make colored highlights in the Font Bakery terminal output.

I don't know why the behavior changed for you after re-installation, however, for a quick fix, to make it useable, you can run fontbakery without colored output `-C` and if the progressbar is an issue as well (See #4182) `-n`. E.g.:

```
$ fontbakery check-googlefonts -C -n path-to-fonts/*.tff
```

From https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.3 I see that:

> PowerShell 7.2 added a new automatic variable, $PSStyle, and changes to the PowerShell engine to support the output of ANSI-decorated text.

So there may be some configuration you could do in your shell to turn on color support, but I don't have Windows, so I won't give you speculative advice on how to do so.
