### ISSUE TITLE
[com.google.fonts/check/family/panose_familytype] and [com.google.fonts/check/family/panose_proportion] FAIL to WARN

### ISSUE THREAD

**Issue by bramstein** [fonttools/fontbakery#4192]
## Observed behaviour

The `com.google.fonts/check/family/panose_familytype` and `com.google.fonts/check/family/panose_proportion` checks are currently included in the `opentype` and `adobefonts` profiles and FAIL when the PANOSE family type and proportion do not match within a family. 

At the Type Founders we have a lot of families that include "extras" as a separate style such as dingbats, borders, icons, and so on. We also have families that cover more than one typographic "family type" but are still consistent in terms of vertical metrics and are intended to be used together. In both cases the PANOSE properties are correctly set to different values for familytype and proportion, however a fail is reported.

## Expected behaviour

While these families may be slightly unusual, it seems rather restrictive to result in a FAIL. As far as I know there are only a handful of applications that actually use PANOSE (happy to be corrected here), so a WARN seems more appropriate. This is especially concerning when it comes to the `adobefonts` profile as it is used by Adobe as a pass/fail test before fonts can be uploaded to their platform.

**Comment by davelab6** [comment]
@bramstein good points, I agree :)

**Comment by bramstein** [comment]
Forgot to add: I'd be happy to make the change and open a PR if there is consensus around it.

**Comment by bramstein** [comment]
@simoncozens Thanks for the reminder, totally slipped my mind! I opened a PR: https://github.com/fonttools/fontbakery/pull/4248
