### ISSUE TITLE
[com.google.fonts/check/varfont/grade_reflow] Should also check ROND axis

### ISSUE THREAD

**Issue by madig** [fonttools/fontbakery#4200]
## Expected behaviour

The ROND axis has recently been added to the axis registry I think, and it similarly shouldn't change advance width. I suppose the check's range could be expanded. Maybe this could even be a parameter in the config?

**Comment by felipesanches** [comment]
Thanks. I'll look into it. I expect any change to the axis registry to affect fontbakery via its `axisregistry` dependency.

**Comment by felipesanches** [comment]
This will probably be fixed by the new 0.4.3 version of that dependency. I'll update requirements.txt later today
