### ISSUE TITLE
check/metadata/parses failures due to outdated fonts_public.proto schema

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4249]
I noticed today that **check/metadata/parses** is failing to parse METADATA.pb files due to it not recognizing the `stroke` field.

![Screenshot from 2023-09-01 07-22-12](https://github.com/fonttools/fontbakery/assets/213676/d598121c-70b0-4205-8a80-14d36498607a)
(source of this screenshot: https://github.com/google/fonts/pull/6652)

This field seems to have been used for the first time on August 4th, on this commit to **google/fonts** repo:
https://github.com/google/fonts/commit/bae7d2f579e7a7f6d0785b8848ca7648294d3464

I also noticed our current schema does not include the `classifications` field.

The latest update to the fonts proto schema was made 10 months ago by @rsheeter when it still did not have these fields:
https://github.com/googlefonts/gftools/pull/639/files

We need to update the `fonts_public.proto` file. Rod, can you provide a copy of the new version of the schema?

**Comment by rsheeter** [comment]
I will ping the folks who added those fields about updating.

**Comment by evanwadams** [comment]
The new fields have been merged.
