### ISSUE TITLE
[com.google.fonts/check/vendor_id] Error with old versions of Beautiful Soup 4

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fontbakery#4270]
## Observed behavior

`com.google.fonts/check/vendor_id` produces an error if Beautiful Soup 4 version 4.0.1 to 4.6.1 or 4.7.0 is installed because of bugs in Beautiful Soup.

## Expected behavior

setup.py specifies `beautifulsoup4>=4.7.1` so `com.google.fonts/check/vendor_id` will never error (assuming Font Bakery is installed properly respecting transitive dependencies).

## Resources and steps needed to reproduce

```
pip install beautifulsoup4==4.6.1 fontbakery==0.9.1
fontbakery check-googlefonts -c com.google.fonts/check/vendor_id NotoSans-Regular.otf
```

The specific font does not matter.

**Comment by felipesanches** [comment]
thanks!
