### ISSUE TITLE
[com.google.fonts/check/license/OFL_body_text] is very strict on formatting

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#4289]
(**NOTE:** Please include the check-id in the issue's title. Check-id example: [com.google.fonts/check/metadata/parses])

## Observed behaviour

🔥 FAIL: Check OFL body text is correct. ([com.google.fonts/check/license/OFL_body_text](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_body_text))
🔥 FAIL The OFL.txt body text is incorrect. Please use https://github.com/googlefonts/Unified-Font-Repository/blob/main/OFL.txt as a template. You should only modify the first line. [code: incorrect-ofl-body-text]

Have this FAIL but the difference between the OFL template we use and the one reported by the FAIL are ignorable:

<img width="1167" alt="Screenshot 2023-09-27 at 15 49 06" src="https://github.com/fonttools/fontbakery/assets/12222436/10a69657-8e9b-42e1-8487-46ff4bdb7b0f">

## Expected behaviour

We want to make sure that the OFL license content has not been modified, but formatting such as that is okay, and doesn't worth a new PR upstream to change their license. I remember we introduced this check because Dave was attached to the formatting of the header to follow exactly this (one empty line and then 2 empty lines):

```
Copyright 20** The My Font Project Authors (https://github.com/googlefonts/googlefonts-project-template)

This Font Software is licensed under the SIL Open Font License, Version 1.1.
This license is copied below, and is also available with a FAQ at:
https://scripts.sil.org/OFL


-----------------------------------------------------------
SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
-----------------------------------------------------------
```
But it also create FAILS we would ignore cause this missing space at the end of the line doesn't worth to be fixed upstream, and then repackage.

## Resources and steps needed to reproduce

Found in https://github.com/google/fonts/pull/6799#issuecomment-1737405567

cc @davelab6

**Comment by felipesanches** [comment]
OK. I can try to improve the check to ignore differences if they only differ in space chars.
