### ISSUE TITLE
Check bounding box of arabic letter high hamza glyph?

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4315]
**com.google.fonts/check/arabic_high_hamza** on the Universal Profile.

According to what was described at #4290, it seems that we should perform additional checking:

Should we also validate the bounding box of U+0674 (the arabic letter high hamza glyph) and compare it to U+0621 (arabic letter hamza) expecting them to have roughly (within a certain tolerance margin) the same size?

**Comment by khaledhosny** [comment]
I think so, yes. Since most fonts make it a composite of hamza above (U+0654), it is possible someone will see the failure message, change the glyph class and think that is it.
