### ISSUE TITLE
make sure description/article display correctly

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#4318]
## What needs to be checked?

In non-noto fonts;
if Article
- Description must not be missing
- Description must be empty
- Article must not be empty

In Noto fonts;
- Article must not be missing nor empty
- Description must not be missing nor empty

## Detailed description of the problem 

The Article directory for non-Noto project is taking over the Description file. To avoid duplicated data, the description needs to be empty (but not removed, it doesn't work if it is removed). More info there: https://googlefonts.github.io/gf-guide/description.html

## Resources and steps needed to reproduce the problem

Kalnia, Onest and Lexend are non-Noto families with articles.

## Suggested profile

Suggest which profile the check should be added to. The most common are:

- [x] Vendor-specific: Google Fonts
- [ ] Vendor-specific: Adobe Fonts
- [ ] OpenType (requirements imposed by the OpenType specification)
- [ ] Universal (broadly accepted best practices on the type design community)
- [ ] Other:

## Suggested result

Which log result level should the check have:

- [x] 🔥 **FAIL** (An issue that must be corrected for the font to function properly)
- [ ] ⚠️ **WARN** (A potential issues that may need to be addressed)

## Severity assessment

5 (the specimen page won't display correctly without this)
(Classify the problem on a scale of 1 (minor) to 5 (major). How "buggy" would the font be considered if it had the problem described?)

**Comment by simoncozens** [comment]
Fixed in #4613.
