### ISSUE TITLE
fontbakery check-... -L does not work

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4320]
```
$ fontbakery check-googlefonts -L
No applicable files found
usage: fontbakery check-googlefonts [-h] [--configuration CONFIGFILE]
                                    [-c CHECKID] [-x EXCLUDE_CHECKID] [-v]
                                    [-l LOGLEVEL] [-m LOGLEVEL_MESSAGES]
                                    [--succinct] [-n] [-C] [-S] [-L] [-F]
                                    [--dark-theme] [--light-theme]
                                    [--timeout TIMEOUT] [--json JSON_FILE]
                                    [--badges DIRECTORY]
                                    [--ghmarkdown MD_FILE] [--html HTML_FILE]
                                    [-g ITERATED_ARG] [-o ORDER] [-J JOBS]
                                    [-j]
                                    [files ...]
```

I just want to list the checks in this profile. I know I can work around it by adding an unnecessary font file at the end, but (a) that's bad UX, and (b) `[files ...]` suggests that this optional.

**Comment by felipesanches** [comment]
Works for me. Which version are you using?

![Screenshot from 2023-10-30 10-37-33](https://github.com/fonttools/fontbakery/assets/213676/b9c387ef-865d-4fd8-9376-26cc6e9ee4c2)

**Comment by felipesanches** [comment]
Also works with latest git main branch.
![Screenshot from 2023-10-30 10-42-01](https://github.com/fonttools/fontbakery/assets/213676/b1b01d19-bf07-4665-b773-804dd8ceb0d1)

**Comment by felipesanches** [comment]
And I remember this was a known bug that had been fixed a while ago (see issue #3878)

**Comment by simoncozens** [comment]
You're right, sorry. I was in a funny venv.

**Comment by felipesanches** [comment]
No worries. All good ;-)
