### ISSUE TITLE
[com.google.fonts/check/glyphsets/shape_languages] Misleading support from Latin_Core

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#4322]
(**NOTE:** Please include the check-id in the issue's title. Check-id example: [com.organization-name/check/something])

## Observed behaviour

I love this experimental check, but a lot of these languages are not really meant to be supported by Latin Core (Hawaiian, Maeshallese, Sicilian, Teso, Ganda, Jola-Fonyi, Nyanja, Wolof). 

* 🔥 **FAIL** GF_Latin_Core/nl_Latn (Dutch): [[31mFAIL[0m: Shaper didn't attach acutecomb to uni0237] [code: failed-language-shaping]
* 🔥 **FAIL** GF_Latin_Core/haw_Latn (Hawaiian): [[31mFAIL[0m: Some base glyphs were missing: ʻ, [31mFAIL[0m: Shaper produced a .notdef] [code: failed-language-shaping]
* 🔥 **FAIL** GF_Latin_Core/mh_Latn (Marshallese): [[31mFAIL[0m: Some base glyphs were missing: Ḷ, ḷ, Ṃ, ṃ, Ṇ, ṇ, Ọ, ọ, [31mFAIL[0m: Some mark glyphs were missing: ◌̣, [31mFAIL[0m: Shaper produced a .notdef] [code: failed-language-shaping]
* 🔥 **FAIL** GF_Latin_Core/scn_Latn (Sicilian): [[31mFAIL[0m: Some base glyphs were missing: Ḍ, ḍ, [31mFAIL[0m: Shaper produced a .notdef] [code: failed-language-shaping]
* 🔥 **FAIL** GF_Latin_Core/teo_Latn (Teso): [[31mFAIL[0m: Some base glyphs were missing: Ɔ, Ɛ, Ɨ, Ʉ, ɔ, ɛ, ɨ, ʉ, ᵃ, ᵉ, ᵋ, ᵒ, ᵓ, ᵘ, ᶤ, ᶶ, ⁱ, [31mFAIL[0m: Shaper produced a .notdef] [code: failed-language-shaping]
* 🔥 **FAIL** GF_Cyrillic_Plus/tg_Cyrl (Tajik): [[31mFAIL[0m: Some base glyphs were missing: ҳ, [31mFAIL[0m: Shaper produced a .notdef] [code: failed-language-shaping]
* 🔥 **FAIL** GF_Cyrillic_Plus/uz_Cyrl (Uzbek (Cyrillic)): [[31mFAIL[0m: Some base glyphs were missing: ҳ, [31mFAIL[0m: Shaper produced a .notdef] [code: failed-language-shaping]
* ⚠ **WARN** GF_Latin_Core/lg_Latn (Ganda): [[33mWARN[0m: No variant glyphs were found for Eng] [code: warning-language-shaping]
* ⚠ **WARN** GF_Latin_Core/dyo_Latn (Jola-Fonyi): [[33mWARN[0m: No variant glyphs were found for Eng] [code: warning-language-shaping]
* ⚠ **WARN** GF_Latin_Core/ny_Latn (Nyanja): [[33mWARN[0m: No variant glyphs were found for Eng] [code: warning-language-shaping]
* ⚠ **WARN** GF_Latin_Core/wo_Latn (Wolof): [[33mWARN[0m: No variant glyphs were found for Eng] [code: warning-language-shaping]
* ⚠ **WARN** GF_Cyrillic_Plus/ku_Cyrl (Kurdish): [[33mWARN[0m: No exemplar glyphs were defined for language Kurdish] [code: warning-language-shaping]
</div></details><br></div></details><details><summary><b>[1] Family checks</b></summary><div><details><summary>ℹ <b>INFO:</b> Check axis ordering on the STAT table. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT/axis_order">com.google.fonts/check/STAT/axis_order</a>)</summary><div>

## Expected behaviour

I think this check will be easier to update when Jan's glyphset definitions are merged in the main branch of the glyphset repo because then we'll have an actual file that lists the languages meant to be supported by Latin_Core. 

I find it very useful that it tests the languages that are "almost" supported though! 
- I would like to keep WARNs for the languages that are supported by the font but not officially supported by Latin_Core
- Also WARNs for languages "almost" supports (like between 1-5 missing glyphs)

## Resources and steps needed to reproduce

Found when testing the fonts in this repo: https://github.com/NaN-xyz/Rubik-Filtered

cc @yanone

**Comment by yanone** [comment]
Maybe just update the language list?
https://github.com/googlefonts/glyphsets/pull/109/files#diff-44efeed2f05af0f346bbafc2379257c9e15e74a43c632a79ab344469b7c3723c

**Comment by felipesanches** [comment]
thanks, @yanone!

**Comment by vv-monsalve** [comment]
The check still reports expectations for languages like Guaraní or Quechua that would belong to the Latin Beyond.

<details><summary>🔥 <b>FAIL:</b> Shapes languages in all GF glyphsets. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyphsets/shape_languages">com.google.fonts/check/glyphsets/shape_languages</a>)</summary><div>

>
>This check uses a heuristic to determine which GF glyphsets a font supports. Then it checks the font for correct shaping behaviour for all languages in those glyphsets.
>
* 🔥 **FAIL** GF_Latin_Core glyphset:

| Language | FAIL messages |
| :--- | :--- |
| gn_Latn (Guarani) | Some base glyphs were missing: ʼ |
|  ^  | Shaper produced a .notdef |
| qu_Latn (Quechua) | Some base glyphs were missing: CHʼ, Kʼ, Pʼ, Qʼ, Tʼ, chʼ, kʼ, pʼ, qʼ, tʼ |
|  ^  | Shaper produced a .notdef |

 [code: failed-language-shaping]
</div></details>

**Comment by RosaWagner** [comment]
@vv-monsalve i think Jan added Guarani in Latin Core because it was an American language with more than 5M speakers. I’ll check later to be sure.

**Comment by yanone** [comment]
Yes, it's defined here: https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/definitions/__init__.py#L20

I added it because it fit the requirements. We can take it out.

**Comment by felipesanches** [comment]
Can we move this discussion to the glyphsets issue tracker?

**Comment by yanone** [comment]
I've already prepared a [PR](https://github.com/googlefonts/glyphsets/pull/155) for glyphsets, so I'm closing this.

The new glyphsets dependency version will come as part of a Fontbakery [PR](https://github.com/fonttools/fontbakery/pull/4380) on another topic that I'm currently finishing.
