### ISSUE TITLE
[com.google.fonts/check/glyphsets/shape_languages] KeyError: 'GF_Cyrillic_Historical'

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4325]
At https://github.com/google/fonts/pull/6943#issuecomment-1795169283:

![Screenshot from 2023-11-07 17-17-17](https://github.com/fonttools/fontbakery/assets/213676/b4637fa2-fa2d-43cf-91fd-b6c09f6406ca)

**Comment by justvanrossum** [comment]
I'm also seeing this, with a different key:
```
Failed with KeyError: 'GF_TransLatin_Pinyin'
```
I assume it is the same bug?
