### ISSUE TITLE
[com.google.fonts/check/metadata/escaped_strings)] Fails for necessary escaped quotes

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fontbakery#4331]
(**NOTE:** Please include the check-id in the issue's title.)

## Observed behaviour

We often have this FAIL for RFN mention that we ignore:

🔥 FAIL: Ensure METADATA.pb does not use escaped strings.

This is the copyright string in METADATA.pb: 
`copyright: "Copyright 2009 The Alike Project Authors (https://github.com/cyrealtype/Alike) with Reserved Font Name \"Alike\" and \"Alike Angular\"."`

## Expected behaviour

I am not sure what this check is trying to ensure because it was implemented a while ago but… Using quotes to define the reserved font name is a standard, and we need escape strings to not break METADATA.pb, therefore this check should pass.

## Resources and steps needed to reproduce

Seen in https://github.com/google/fonts/pull/6929

**Comment by felipesanches** [comment]
> I am not sure what this check is trying to ensure

As described on the original check proposal at https://github.com/googlefonts/gftools/issues/211, it is meant to avoid strings like this: `Juli\303\241n` when it should have proper unicode strings like this: `Julián`

**Comment by felipesanches** [comment]
Escaping quotes sounds fine, though. I can tweak the check to not FAIL on escaped quotes.
