### ISSUE TITLE
[com.adobe.fonts/check/postscript_name] HTML output is unreadable

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fontbakery#4346]
## Observed behaviour

The HTML output includes an unreadable blob of text with no new lines:

>| Field | Value | Recommendation | |:----- |:----- |:-------------- | | Postscript Name | FooNarrowI-Stuff-Stuff | May contain not more than a single hyphen. | | Postscript Name | FooNarrowI-Stuff-Stuff | May contain not more than a single hyphen. | [code: bad-psname-entries]

## Expected behaviour

The text should be readable (it looks like it is supposed to be formatted as a table).

**Comment by felipesanches** [comment]
I just noticed that it also affects **com.google.fonts/check/glyphsets/shape_languages**

**Comment by felipesanches** [comment]
OK, I've just found the solution!

To get table support (and many other nice things from extensions) one has to use the method `cmarkgfm.github_flavored_markdown_to_html` instead.

**Comment by felipesanches** [comment]
![Screenshot from 2023-11-30 23-48-17](https://github.com/fonttools/fontbakery/assets/213676/ae65c3de-aa55-4e70-b7e9-5e1c00b18778)
![Screenshot from 2023-11-30 23-47-57](https://github.com/fonttools/fontbakery/assets/213676/3026a0da-a42d-4800-b622-f63adfc3dc8d)

**Comment by khaledhosny** [comment]
Looks good, thanks!
