### ISSUE TITLE
OFL website has a new URL and FontBakery should be aware of it

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4358]
According to https://github.com/google/fonts/issues/7062, FontBakery checks should accept the new URL for the OFL website.

**Comment by n7s** [comment]
I have the beginning of a check for that. I'm learning the subtleties of FontBakery, but I'm not able to figure out how to have a check be only a family or repo check. IOW it's giving me the results for all the fonts in the folder so the report info is duplicated, any pointers, thanks.

**Comment by n7s** [comment]
This is as far as I got:
![is_OFL_URL_current-check](https://github.com/fonttools/fontbakery/assets/4881499/d78e3926-020e-44f8-aa6f-b845b858366d)

**Comment by felipesanches** [comment]
Cool! Please submit your work-in-progress as a pull request and I can help you improve it.

**Comment by n7s** [comment]
Thanks, I will prep the PR very soon. I really appreciate all your work on FontBakery! In our current workflow we run FontBakery with a wildcard over all generated fonts in a single project, so even if I use `family_directory`, I get the repeated results per font. Looking forward to finding a workaround or a better solution.

**Comment by m4rc1e** [comment]
I've just amended the license_url check so a warn is raised if the old url is used, https://github.com/fonttools/fontbakery/pull/4409/commits/b297247f65b113ca7622e9fa7a33adbcf9c93f94

**Comment by felipesanches** [comment]
thanks, everybody ;-)

**Comment by simoncozens** [comment]
Hi @n7s, any progress on that PR? If you want to put up what you have, I would be happy to take it over.

**Comment by simoncozens** [comment]
Sorry, we're fine, the PR from Dave got merged before I saw this.
