### ISSUE TITLE
New check: Upper and Lower case character pairs exist together universally

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#4369]
Per https://github.com/google/fonts/issues/7090 we have fonts published with uppercase characters but no corresponding lowercase character, which is a pretty bad bug because shifting cases is very common (eg there's CSS properties to do it.)

So there should be a check to ensure, if there is an uppercase character, there is a corresponding lowercase character, and vice verse. 

This probably belongs in the Universal profile, and I think is worth a 🔥 **FAIL** result, with a level 4 severity.

I'm assigning to Simon, as my first question is, does Unicode provide the upper-lower case linking data we need to power this check?

**Comment by simoncozens** [comment]
Yeah, it's in CaseFolding.txt. Also we have #3230 already, closing in favour of that. ;-p
