### ISSUE TITLE
[com.google.fonts/check/varfont/boldwghtcoord] should not require an fvar `Bold` instance

### ISSUE THREAD

**Issue by vv-monsalve** [fonttools/fontbakery#4373]
## Observed behavior

> 🔥 FAIL "Bold" instance not present. [code: no-bold-instance]

By the above message, the check seems to be assuming there should be a Bold companion for the Regular font, where that is not mandatory.

On the other hand, the Rationale is somehow misleading. 

> The Open-Type spec's registered design-variation tag 'wght' available at https://docs.microsoft.com/en-gb/typography/opentype/spec/dvaraxistag_wght does not specify a required value for the 'Bold' instance of a variable font.
> 
> But Dave Crossland suggested that we should enforce a required value of 700 in this case (NOTE: a distinction is made between "no bold instance present" vs. "bold instance is present but its wght coordinate is not == 700").

Whereas the linked section of the Spec doesn't directly specify the required values, it provides a value interpretation reference related to the [usWeightClass](https://learn.microsoft.com/en-gb/typography/opentype/spec/os2#usweightclass) field of the `OS/2` table where the 700 value for Bold is defined. So, the usWeightClass is the source of truth for the 700 value requirement.

## Expected behavior

- Since a font can have a weight range that doesn't include a Bold instance (e.g. 100--400) this instance shouldn't be required.
- For the rationale to be updated.

## Resources and steps needed to reproduce

The font triggering this failure is still a private project. However, this has also been reported in this [comment on #3818](https://github.com/fonttools/fontbakery/issues/3818#issuecomment-1172259388)

**Comment by vv-monsalve** [comment]
This is still being reported. 
@simoncozens

**Comment by guidoferreyra** [comment]
@simoncozens Despite I don‘t love how the check is written (it only looks for an instance as "Bold" ignoring others like "Text Bold", "Condensed Bold" etc. To me it makes sense to have a check for bold being on the correct coordinate. As you said is not on the OT spec but is relevant for CSS. 
Because using  "font-weight: bold" on a VF renders 700 cordinate.

**Comment by simoncozens** [comment]
Sure, it's fine to have this on the "universal" profile. But the "opentype" profile is driven by the OT spec, and that doesn't define coordinate values.

**Comment by guidoferreyra** [comment]
Right! Somehow I confused "Opentype" with "Universal"

**Comment by vv-monsalve** [comment]
> This check shouldn't be on the "opentype" profile.

Did you see my comment above?:

> Whereas the linked section of the Spec doesn't directly specify the required values, it provides a value interpretation reference related to the [usWeightClass](https://learn.microsoft.com/en-gb/typography/opentype/spec/os2#usweightclass) field of the OS/2 table where the 700 value for Bold is defined. So, the usWeightClass is the source of truth for the 700 value requirement.
