### ISSUE TITLE
Add a FATAL check status

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4374]
### Discussed in https://github.com/fonttools/fontbakery/discussions/4364

<div type='discussions-op-text'>

<sup>Originally posted by **m4rc1e** December  7, 2023</sup>
I'd like a new check status which is even more severe than FAIL. It should be named something like FATAL! This status should be used for checks which are essential for a family to successfully get onboarded to Google Fonts such as metadata files parsing correctly.

Implementing this check status will allow me to finally set the google/fonts ci to fail. I don't want to raise error codes on just FAILs since they are too strict and will fail many older families.

Discussion triggered by https://github.com/google/fonts/issues/7078

cc @chrissimpkins 

</div>

**Comment by felipesanches** [comment]
![Screenshot from 2023-12-13 02-57-41](https://github.com/fonttools/fontbakery/assets/213676/9a51fbaa-bc4b-4d69-8662-cd841d618d71)

**Comment by felipesanches** [comment]
![Screenshot from 2023-12-13 03-53-10](https://github.com/fonttools/fontbakery/assets/213676/c03001db-45ac-4467-a1d7-f631f1e26758)

**Comment by m4rc1e** [comment]
Love it. Thank you very much!

**Comment by felipesanches** [comment]
I think we may want to delete the severity field on checks. And only move things from FAIL to FATAL, or leave them as FAILs.

It gets confusing to have multiple mechanisms for declaring how bad it is not to pass a check.

**Comment by felipesanches** [comment]
Also, I am not sure how to communicate to a CI job the difference between a FAIL and a FATAL. FontBakery, for now, still emits error code 1 if there's any FAIL check result (or worse).

Deciding when to break a CI job is a decision of the user (the CI job setup) and not the tool itself.

**Comment by m4rc1e** [comment]
> FontBakery, for now, still emits error code 1 if there's any FAIL check result (or worse).

Why not introduce a cli arg such as `--error-code-on` which has the choices (WARN, FAIL, FATAL)?

**Comment by felipesanches** [comment]
Yes! Sounds reasonable. I was thinking of doing something like that. I'm glad someone else also had a similar idea. :-)

**Comment by vv-monsalve** [comment]
> I think we may want to delete the severity field on checks. And only move things from FAIL to FATAL, or leave them as FAILs.
> 
> It gets confusing to have multiple mechanisms for declaring how bad it is not to pass a check.

The severity indicated how broken a _font_ would be if that check's issue was not implemented.

Whereas I see the `FATAL` result will be related to how broken the _pipeline workflow_ (servers push) would be by the unattended issues.
