### ISSUE TITLE
Customize reporters to highlight FATAL results

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4377]
After #4374, we now should customize the reporters so that users get very visibility of any FATAL results.

For instance, on the GitHub Markdown report, the FATAL results might be placed directly on the body of the report, instead of inside a collapsed region.

**Comment by davelab6** [comment]
Excellent idea

**Comment by simoncozens** [comment]
If there are any FATALs, they should be the only things displayed. A FATAL suggests that the rest of the checks are unreliable/redundant.

**Comment by felipesanches** [comment]
> If there are any FATALs, they should be the only things displayed. A FATAL suggests that the rest of the checks are unreliable/redundant.

I agree. But I remember @davelab6 rejecting this idea in two different conversations about this, so I'd like to double-check with him if he'd accept such a drastic approach.
