### ISSUE TITLE
[com.google.fonts/check/interpolation_issues] update FontBakery check to match recent changes in fonttools/varLib.interpolatable

### ISSUE THREAD

**Issue by MariannaPaszkowska** [fonttools/fontbakery#4388]
**com.google.fonts/check/interpolation_issues**
**update FontBakery check to match recent changes in fonttools/varLib.interpolatable**

Hi, we noticed that this check only checks for a couple of issues, such as "contour order" and "wrong start point". 
I think that it would be great if it could also include some of @behdad 's recent improvements in fonttools/varLib.interpolatable, like "kink", "underweight", and "overweight" warnings.  

Please note that the "overweight" is not yet released, but it is expected soon.

**Comment by behdad** [comment]
FontTools got a release now. The wheels are building. For the "overweight" test I have not been able to get a good algorithm yet.

**Comment by simoncozens** [comment]
Fixed in #4615.
