### ISSUE TITLE
gh markdown report looks broken

### ISSUE THREAD

**Issue by m4rc1e** [fonttools/fontbakery#4399]
Hope you've had a great xmas and nye.

I've just noticed that the ghmarkdown looks a little broken in https://github.com/google/fonts/pull/7143#issuecomment-1875578660

<img width="835" alt="Screenshot 2024-01-03 at 15 53 14" src="https://github.com/fonttools/fontbakery/assets/7525512/cf6bbe1d-e4d4-4738-9a91-6ed429f9adac">

I thought it may be gftools qa, but when I run just fb using the `--ghmarkdown` arg, I get the same results.

**Comment by felipesanches** [comment]
Thanks, @m4rc1e! I'll take a look.

I hope you had great end of year celebrations as well!

**Comment by simoncozens** [comment]
The "border" line was not updated after the new FATAL was added. Ideally we would be using a Markdown table generation library, rather than having to update this kind of thing manually.

**Comment by moyogo** [comment]
https://github.com/fonttools/fontbakery/pull/4390 should have fixed this. Can you try the main branch version?

**Comment by simoncozens** [comment]
Yeah, looking at https://github.com/google/fonts/pull/7162 this is now fixed.
