### ISSUE TITLE
[com.google.fonts/check/family/win_ascent_and_descent] seems to require winAscent to exceed UPM

### ISSUE THREAD

**Issue by ryanbugden** [fonttools/fontbakery#4404]
## Observed behavior

- I have a UFO that has a `font.bounds[3]` of 980 and a `font.info.unitsPerEm` of 1000. 
- I set the `winAscent` to 980. 
- This check fails with `🔥 FAIL OS/2.usWinAscent value should be equal or greater than 1000, but got 980 instead [code: ascent]`. 
- It seems to expect winAscent to necessarily exceed the UPM.

## Expected behavior

I expected this check to pass, as 980 is the highest point in the UFO.

**Comment by glenda-tn** [comment]
Hi @ryanbugden The check is run on binaries so check to make sure the `ymax` is what you expect (980) in the fonts. (Font Table Viewer is a good tool
for this.) There might be an interpolation error or something that isn’t showing up in the UFOs but is in a generated instance. Good luck.

**Comment by ryanbugden** [comment]
@glenda-tn Good point, I should've double-checked the binary. Looks like the `head` table has a `ymax` of 1000. And it looks like it's from an auto-generated `.notdef` glyph. Thank you! Closing the issue.

```xml
  <head>
    <!-- Most of this table will be recalculated by the compiler -->
    <tableVersion value="1.0"/>
    <fontRevision value="1.0"/>
    <checkSumAdjustment value="0xc3aca27f"/>
    <magicNumber value="0x5f0f3cf5"/>
    <flags value="00000000 00000011"/>
    <unitsPerEm value="1000"/>
    <created value="Fri Jan  5 11:54:37 2024"/>
    <modified value="Fri Jan  5 16:54:37 2024"/>
    <xMin value="-227"/>
    <yMin value="-90"/>
    <xMax value="1343"/>
    <yMax value="1000"/>
    <macStyle value="00000000 00000000"/>
    <lowestRecPPEM value="3"/>
    <fontDirectionHint value="2"/>
    <indexToLocFormat value="0"/>
    <glyphDataFormat value="0"/>
  </head>
  ```
