### ISSUE TITLE
[com.adobe.fonts/check/varfont/same_size_instance_records] FAIL if the font has no named instances

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fontbakery#4410]
## Observed behaviour

A variable font without any named instances gets a FAIL in com.adobe.fonts/check/varfont/same_size_instance_records with s misleading message:

> 🔥 FAIL Instance records don't all have the same size. [code: different-size-instance-records]

## Expected behaviour

A fount without instances should not FAIL.

## Resources and steps needed to reproduce

Here is a font that currently FAILs: [RaqqSura.zip](https://github.com/fonttools/fontbakery/files/13893080/RaqqSura.zip)

**Comment by felipesanches** [comment]
thanks, @khaledhosny
