### ISSUE TITLE
[com.google.fonts/check/license/OFL_body_text] Check should allow new OFL homepage

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4412]
In `OFL_BODY_TEXT`, change `https://scripts.sil.org/OFL` to https://openfontlicense.org/
(Similarly in `PLACEHOLDER_LICENSING_TEXT`.)

(See https://github.com/google/fonts/pull/7104#issuecomment-1855608264)

**Comment by felipesanches** [comment]
Both old and new URLs should be accepted. Perhaps the old one could cause a WARN.

**Comment by felipesanches** [comment]
This is a duplicate of #4358
