### ISSUE TITLE
[com.google.fonts/check/arabic_spacing_symbols] Include U+FBC2 ARABIC SYMBOL WASLA ABOVE

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fontbakery#4417]
## Observed behavior

`com.google.fonts/check/arabic_spacing_symbols` does not check U+FBC2 ARABIC SYMBOL WASLA ABOVE.

## Expected behavior

`com.google.fonts/check/arabic_spacing_symbols` should check U+FBC2 ARABIC SYMBOL WASLA ABOVE, as requested in #4295.

**Comment by felipesanches** [comment]
thanks, @dscorbett
