### ISSUE TITLE
FontBakery crashes or does not terminate when no matching checks are found

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#4420]
In https://github.com/fonttools/fontbakery/discussions/4398 there is a crash report - I am surprised to see a crash, not an ERROR, so I'd like to give this the highest priority, as it seems trivial to fix :)

<div type='discussions-op-text'>

<sup>Originally posted by **Hoolean** January  1, 2024</sup>
When specifying check IDs manually on the command line, FontBakery crashes or does not terminate when there are no checks matching the given IDs.

## Reproducing

1. Obtain a TTF:
    * e.g. [NotoSansEgyptianHieroglyphs-Regular.ttf](https://notofonts.github.io/#egyptian-hieroglyphs)
    
2. Install the latest version of FontBakery:
    ```bash
     python3 -m venv venv
     . venv/bin/activate
     pip install fontbakery
     ```
3. Run FontBakery on the TTF, specifying a check ID that does not exist:
    1. In serial:
     ```bash
     fontbakery check-universal NotoSansEgyptianHieroglyphs-Regular.ttf --check thisdoesnotexist
     ```
    2. In parallel:
      ```bash
      fontbakery check-universal NotoSansEgyptianHieroglyphs-Regular.ttf --check thisdoesnotexist --auto-jobs
      ```

## Expected result

FontBakery shows an error message, or exits with a report showing that 0 tests were performed.

## Actual result

* Depending on how FontBakery was invoked:

    1. In serial: FontBakery crashes on completion:
    ```
    Start ... running 0 individual check executions.

    Total:
    
        ERROR: 0
        FATAL: 0
        FAIL: 0
        WARN: 0
        INFO: 0
        SKIP: 0
        PASS: 0
    
    []   0%
    
    DONE!
    
    ...
    
    Traceback (most recent call last):
      File "/home/harryd/Experiments/fontbakery-stall/venv/bin/fontbakery", line 8, in <module>
        sys.exit(main())
      File "/home/harryd/Experiments/fontbakery-stall/venv/lib/python3.10/site-packages/fontbakery/cli.py", line 61, in main
        run_profile_check(subcommand_module[6:])
      File "/home/harryd/Experiments/fontbakery-stall/venv/lib/python3.10/site-packages/fontbakery/cli.py", line 34, in run_profile_check
        sys.exit(check_profile_main(module.profile))
      File "/home/harryd/Experiments/fontbakery-stall/venv/lib/python3.10/site-packages/fontbakery/commands/check_profile.py", line 473, in main
        return 1 if tr.worst_check_status.weight >= args.error_code_on.weight else 0
    AttributeError: 'NoneType' object has no attribute 'weight'
    ```
    2. In parallel: FontBakery blocks forever and never terminates:
    ```
    Start ... running 0 individual check executions.

        ERROR: 0
        FATAL: 0
        FAIL: 0
        WARN: 0
        INFO: 0
        SKIP: 0
        PASS: 0
        (not finished): 0
    
    ░ []   0%
    ```

## Environment

* Python: 3.10.12
* FontBakery: 0.10.8 release
* OS: Ubuntu 22.04.3 LTS (WSL)</div>

**Comment by felipesanches** [comment]
The check runner protects us from crashes by emitting an ERROR when something goes bad on a check implementation.
But this one is an actual crash instead of an ERROR because it is a bug in the engine itself.

I agree that it is likely trivial to fix. I'll try to address the problem now.

**Comment by Hoolean** [comment]
Cheers Dave for promoting this to an issue, and Felipe for the speedy patch 🚀 

I just tested the new commit: FontBakery no longer crashes when running the checks in serial, but still becomes deadlocked when running the checks in parallel, and so that case may require a further fix.

```bash
$ python3 -m venv venv
$ . venv/bin/activate

$ pip install git+https://github.com/fonttools/fontbakery.git@ca92411ebf77597da21497157edeaf47295e5da5

$ fontbakery check-universal NotoSansEgyptianHieroglyphs-Regular.ttf --check thisdoesnotexist --auto-jobs
Start ... running 0 individual check executions.

    ERROR: 0
    FATAL: 0
    FAIL: 0
    WARN: 0
    INFO: 0
    SKIP: 0
    PASS: 0
    (not finished): 0

░ []   0%
# does not terminate
```

**Comment by felipesanches** [comment]
fixed!

**Comment by Hoolean** [comment]
Woo, fantastic! Thanks again :)
