### ISSUE TITLE
[com.google.fonts/check/contour_count] Basic glyphs and their derived (e.g. diacriticized) glyphs are checked inconsistently

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fontbakery#4433]
## Observed behavior

`com.google.fonts/check/contour_count` has inconsistent requirements for the homologous pieces of the glyphs of related characters. For example, it expects the glyph for U+1E56 LATIN CAPITAL LETTER P WITH DOT ABOVE to have exactly 3 contours, but the glyph for U+0050 LATIN CAPITAL LETTER P can have 1 or 2 contours.

## Expected behavior

`com.google.fonts/check/contour_count` should understand that some glyphs are intentionally based on other glyphs. For example, `uni1E56` should not be defined to have exactly 3 contours, nor to have either 2 or 3 contours, but instead to have 1 + however many contours `P` has. That way, if there is a font where `P` intentionally has an unusual number of contours, Font Bakery would warn only for `P`, not for all glyphs based on `P` with a diacritic.

## Resources and steps needed to reproduce

```console
pip install fontbakery==0.10.9
curl -LO https://github.com/aliftype/amiri/releases/download/1.000/Amiri-1.000.zip
unzip Amiri-1.000.zip
fontbakery check-googlefonts -c com.google.fonts/check/contour_count Amiri-1.000/Amiri-Regular.ttf
```

**Comment by felipesanches** [comment]
"uni1E56 should not be defined to have exactly 3 contours, nor to have either 2 or 3 contours, but instead to have 1 + however many contours P has. That way, if there is a font where P intentionally has an unusual number of contours, Font Bakery would warn only for P, not for all glyphs based on P with a diacritic."

On the other hand, maybe we could prototype an experimental check that is smarter the way you described here. I'm just afraid I am not sure yet how to make it broad enough to be justifiable. I do not want to implement a tiny check for just a single limited/specific case.
