### ISSUE TITLE
New check: Kerning of tabular glyphs

### ISSUE THREAD

**Issue by yanone** [fonttools/fontbakery#4440]
## What needs to be checked?

Check that tabular glyphs (numerals, mathematic, perhaps some punctuation) show no kerning in combination with all other glyphs

## Detailed description of the problem 

Extensive font projects can be untidy and accidentally contain kerning of tabular glyphs.

## Resources and steps needed to reproduce the problem

This check is conditional on the existence of tabular glyphs in the font.

We need to first find all tabular glyphs, then run shaping of all glyphs in the font with the tabular glyphs to check for existence of kerning. This would include self-intersecting checking of the tabular glyphs against each other, the main point of tabular glyphs. But even regular proportional glyphs shouldn't be kerned with tabular glyphs.

In order to find all tabular glyphs other than numerals,
* for fonts with a `tnum` feature I would use all target glyphs of `tnum` substitutions,
* for plain fonts without `tnum` I would first read what the width of the tabular numerals are, if any, then collect all glyphs that show the same width as the tabular glyphs. This might include some false identicals for proportional fonts and thus might cause some false positives for this check. I want to use this wholesale approach rather than limiting tabular glyphs to strictly being numerals or math signs per Unicode definition because a font project may decide for any glyphs to be tabular to be used in a table.

Then, all glyphs in the font combined with all tabular glyphs would be typeset in Harfbuzz and checked for applied kerning.

## Suggested profile

Suggest which profile the check should be added to. The most common are:

- [ ] Vendor-specific: Google Fonts
- [ ] Vendor-specific: Adobe Fonts
- [ ] OpenType (requirements imposed by the OpenType specification)
- [X] Universal (broadly accepted best practices on the type design community)
- [ ] Other:

## Suggested result

Which log result level should the check have:

- [X] 🔥 **FAIL** (An issue that must be corrected for the font to function properly)
- [ ] ⚠️ **WARN** (A potential issues that may need to be addressed)

## Severity assessment

(Classify the problem on a scale of 1 (minor) to 5 (major). How "buggy" would the font be considered if it had the problem described?):

5: broken

**Comment by juandelperal** [comment]
Hi there

I've noticed that our kerning check is occasionally producing false positives, particularly when examining kerning in tabular numbers.

<img width="753" alt="image" src="https://github.com/fonttools/fontbakery/assets/2414972/606eab06-3b31-4ed3-9d80-0c5f5d59cd51">

In this case, kerning is present between D and Ž components within the first glyph, but not between Ǆ and the numbers. Maybe that's the reason we are getting misleading results.

Thanks!
