### ISSUE TITLE
New check: Check that Roman and Italic fonts have the same axis setup

### ISSUE THREAD

**Issue by yanone** [fonttools/fontbakery#4445]
## What needs to be checked?

Check that Roman and Italic fonts have the same axis setup

## Detailed description of the problem 

Fontbakery didn't catch that [Ubuntu Sans Mono](https://github.com/canonical/Ubuntu-Sans-Mono-fonts/tree/main/fonts/variable) has a weight range of 400-700 for the Italic but 100-700 for the Roman. I was hindered to onboard the fonts to Google Fonts by the packager, which apparently includes such as check, but not by Fontbakery. This mistake should have been caught earlier in the Fontbakery stage.

I'm not sure inhowfar axes really need to be identical between Roman and Italic, so we may want to discuss this first.

## Suggested profile

Suggest which profile the check should be added to. The most common are:

- [ ] Vendor-specific: Google Fonts
- [ ] Vendor-specific: Adobe Fonts
- [ ] OpenType (requirements imposed by the OpenType specification)
- [X] Universal (broadly accepted best practices on the type design community)
- [ ] Other:

## Suggested result

Which log result level should the check have:

- [X] 🔥 **FAIL** (An issue that must be corrected for the font to function properly)
- [ ] ⚠️ **WARN** (A potential issues that may need to be addressed)

(Not sure, tho)

## Severity assessment

(Classify the problem on a scale of 1 (minor) to 5 (major). How "buggy" would the font be considered if it had the problem described?)

(Not sure)

**Comment by yanone** [comment]
Seems like ranges of axes should be identical across all axes in a family. I plan to take the code out of the gftools packager and put it into a FB check.

**Comment by felipesanches** [comment]
thanks, @yanone
