### ISSUE TITLE
`--succinct` has some spurious output that may indicate bugs

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4451]
![Screenshot from 2024-01-26 12-12-01](https://github.com/fonttools/fontbakery/assets/213676/86e879b5-16a5-4f3a-96a5-b966c126db28)

This needs further investigation:

* I don't know yet what that `0.0 0.0` is;
* And I suppose that `UserWarning: No such subset 'menu'` may be a bug in the gfsubsets package.

**Note**: I'm also not sure if this only shows up with `--succinct`, but its smaller volume of output may have just made it easier for me to notice the spurious messages.

**Comment by felipesanches** [comment]
@simoncozens maybe this is also related to #4447 ?

**Comment by simoncozens** [comment]
The 0.0 is a print statement in (IIRC) an Italic angle check.

**Comment by simoncozens** [comment]
> And I suppose that UserWarning: No such subset 'menu' may be a bug in the gfsubsets package.

It's just a horrible artefact of how subsets work. Fonts must declare that they support the `menu` subset in the metadata.pb, so gfsubsets tries to load it, but menu is an "internal" subset that we don't have a public definition for, so gfsubsets can't find it and complains. Everybody's doing the right thing, it's just not a great situation.

At any rate nothing left to be done on the fontbakery side.
