### ISSUE TITLE
`--loglevel` behaviour changed?

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4452]
`-l WARN` should display `WARN` **or worse**. But it is now displaying only the results that are `WARN`s, and omitting the `FAIL`s

@simoncozens, this may have been a bug introduced at #4447 

![Screenshot from 2024-01-26 12-25-00](https://github.com/fonttools/fontbakery/assets/213676/438eb28a-9712-4f2e-8ba3-2f948387e58a)

**Comment by simoncozens** [comment]
I already have a fix for this, will PR soon.

**Comment by felipesanches** [comment]
thanks!

**Comment by simoncozens** [comment]
Fixed in #4453.
