### ISSUE TITLE
Reporter protocol refactor broke (just slightly) the layout of the terminal reporter

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4454]
**BEFORE:**
![Screenshot from 2024-01-29 13-33-42](https://github.com/fonttools/fontbakery/assets/213676/468cb316-a213-4b37-ae37-d394f594cadb)

**AFTER:**
![Screenshot from 2024-01-29 13-33-05](https://github.com/fonttools/fontbakery/assets/213676/43e8f1f8-8d11-43f3-b06b-348dc5c713fc)

This needs fixing before cutting any new release.

_Originally posted by @felipesanches in https://github.com/fonttools/fontbakery/issues/4453#issuecomment-1915089863_

**Comment by simoncozens** [comment]
(For my reference) Issues are:

* Extra newline before rationale
* Extra newline(s!) after rationale
* Newline between status and message
* Subresults not filtered
* No message code

**Comment by felipesanches** [comment]
thanks!
