### ISSUE TITLE
Fontbakery 0.11.0: jinja2 error (fontbakery.reporters not understandable)

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4479]
### Discussed in https://github.com/fonttools/fontbakery/discussions/4476

<div type='discussions-op-text'>

<sup>Originally posted by **eweracs** February  2, 2024</sup>
Hello, this morning, I updated to Fontbakery 0.11.0. Unfortunately, Fontbakery is unable to generate the HTML reports as it runs into an issue with Jinja2. I updated Jinja2 to the latest version.

`ValueError: The 'fontbakery.reporters' package was not installed in a way that PackageLoader understands.`

Is there anything I can do on my end? I have currently downgraded to Fontbakery 0.10.9, which works fine.
OS: macOS 14.2.1
Python: 3.10.2
Jinja2: 3.1.3

Thanks for any pointers!</div>

**Comment by juandelperal** [comment]
Same here
