### ISSUE TITLE
Possible bug? fontbakery.com

### ISSUE THREAD

**Issue by panosvassiliou** [fonttools/fontbakery#4488]
### Discussed in https://github.com/fonttools/fontbakery/discussions/4487

<div type='discussions-op-text'>

<sup>Originally posted by **panosvassiliou** February  5, 2024</sup>
For the last couple of days the online version is on 'loading mode', it doesn't start. Is this a bug, is there something I should do to get it started?

![Screenshot 2024-02-05 at 10 05 32 AM](https://github.com/fonttools/fontbakery/assets/72914151/6f86923b-54ce-4811-82f6-04289edab18a)
</div>

**Comment by simoncozens** [comment]
Yeah, I changed a lot of things in the FB core so it's likely the web version didn't catch up. I'll look at it now.

**Comment by simoncozens** [comment]
Fixed it.

**Comment by panosvassiliou** [comment]
Great, thanks, it works
