### ISSUE TITLE
Terminal output gets intermitently corrupted if using `-J <n>` or `--auto-jobs`

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4494]
I had never before seen what happens to the progress bar on the terminal reporter when we use `--auto-jobs`.

I noticed today, while investigating issue #4481, that the terminal output sometimes gets all messed up because multiple jobs try to render their check results simultaneously. The drawing of the progress bar is significantly broken:

![Screenshot from 2024-02-05 17-34-38](https://github.com/fonttools/fontbakery/assets/213676/b6e64413-10ee-4c63-8179-be2d2c40c511)

But it is also intriguing that the bug seems to be intermittent. Some runs are perfectly fine and some other runs trigger the bug. Perhaps it is a race condition in which some ANSI control sequences are broken by another process printing simultaneously.

**Comment by simoncozens** [comment]
Fixed in #4520.
