### ISSUE TITLE
[GoogleFonts] New METADATA checks on minisite_url keys

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#4504]
I noticed a couple of problems with ofl/climatecrisis/METADATA.pb just now, that I fixed in https://github.com/google/fonts/pull/7268

1. https://github.com/google/fonts/blob/9be2d53f1637defccb19f200a7a0198f1fb96d11/ofl/climatecrisis/METADATA.pb#L31 is a duplicate with https://github.com/google/fonts/blob/9be2d53f1637defccb19f200a7a0198f1fb96d11/ofl/climatecrisis/METADATA.pb#L34  and that is not fatal (due to the way protobufs work) but still should not be possible to land on the main branch
2. L31 had a trailing `/index.html` (and index.* is fairly common and the same issue)
3. A trailing `/` is also the same issue

I can also think of a few other common issues, with the start of the URL string rather than the end:

4. The URL protocol is `http://` but should be `https://` unless that doesn't work at all but insecure http does work, and in this case we should use it even though it is sad to see (because insecure protocol are bad for everyone.)

5. The URL includes a subdomain `www.` that is not needed, the site works fine without it, so drop it.

**Comment by felipesanches** [comment]
I've removed the "Five minute fix" label, because this is not really a 5-minute fix.

I've added the "Work on next" label because I'm going to work on this next (after finishing the work on reviewing the big-refactor in PR #4507)

**Comment by felipesanches** [comment]
For the duplicated `minisite_url` entries, I think we'll have to read the raw text content of the METADATA.pb file, instead of parsing it with the protobuf library because, otherwise, I think the lib would automatically de-duplicate it.
