### ISSUE TITLE
[core] Restructure check result feedback in a more humane way?

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#4505]
In https://forum.glyphsapp.com/t/variable-font-origin/24441/11 Jens K suggests a more humane way to provide check result feedback. I'm not sure what to do exactly, but having just come across the nuggest of wisdom and knowing @simoncozens is working on fb core, I thought I'd post a note about it here :)

**Comment by simoncozens** [comment]
I just realised this is the same as #4241. But in general, yes, I am planning to revisit all the checks and ensure that they report:

* what is the problem
* how we know this font has the problem
* why is it a problem
* how you fix it
