### ISSUE TITLE
fontbakery.com crash, site is currently not useable

### ISSUE THREAD

**Issue by glenda-tn** [fonttools/fontbakery#4509]
## Observed behaviour
![Screen Shot 2024-02-09 at 12 10 35 PM](https://github.com/fonttools/fontbakery/assets/93950887/7ffc3718-0780-43c7-8cfc-0ce666bc7567)

(Describe the results you're getting)

## Expected behaviour

(Describe what you expected to happen, or wished was different)

## Resources and steps needed to reproduce

(Provide the font file that causes the issue, and the exact steps to reproduce it. Also mention the FontBakery version you're using, and some details about your system, e.g. OS, Python version, etc.)

**Comment by simoncozens** [comment]
Sorry; I fixed it!
