### ISSUE TITLE
Bug report, fontbakery.com

### ISSUE THREAD

**Issue by panosvassiliou** [fonttools/fontbakery#4510]
Hello,
cannot test fonts online, on loading it returns the attached message
please advise, thanks

![Screenshot 2024-02-12 at 1 36 45 AM](https://github.com/fonttools/fontbakery/assets/72914151/0d34ace8-3df0-4703-a756-5e0bd08abea1)

**Comment by simoncozens** [comment]
Sorry; I fixed it!
