### ISSUE TITLE
[com.google.fonts/check/fontbakery_version] Development versions not parsed correctly

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4511]
## Observed behaviour

```
Current FontBakery version is 0.11.1.dev1+g7f28eca2.d20240202, while  a newer 0.11.1 is already available.
```

## Expected behaviour

 0.11.1.dev1 is newer then 0.11.1, so this should be a PASS.

Perhaps using standard version parsing libraries (`packaging.version.parse`) would get this right and cut down on code.

**Comment by felipesanches** [comment]
If you `pip install -e .[all]`, then the scm module will set the version to 0.11.2.dev-something

For me, on main branch, the version now is `0.11.2.dev40+gce0d40cc.d20240207`

**Comment by felipesanches** [comment]
0.11.1.dev1+g7f28eca2.d20240202 is not newer than 0.11.1

These `.dev<n>+git-hash` suffixes denote that there are N commits in the development of would in the future become version 0.11.1

I think what is actually missing is for you to fetch the v0.11.1 git tag by doing something like `git fetch upstream; git rebase upstream/main`

Once the tag is available on your local repo, then setuptools_scm will understand that the base version number is now `0.11.2`

**Comment by felipesanches** [comment]
I believe the check implementation is actually correct, so I'll close this issue. Please reopen the issue if you think that's incorrect.
