### ISSUE TITLE
Look into truncated JSON when `--auto-jobs` is given

### ISSUE THREAD

**Issue by IvanUkhov** [fonttools/fontbakery#4513]
Hello,

With Font Bakery 0.11+, we are seeing corrupted JSON files (`--json`) when `--auto-jobs` is given. It is as if the process did not finish writing or flushing. After removing `--auto-jobs`, it seems to work as expected.

**Comment by IvanUkhov** [comment]
Duplicate of #4494. Sorry. Did not see it before.

**Comment by simoncozens** [comment]
Yeah, this is a duplicate of #4494 - multithreading is currently unstable. I should be able to improve it now the conditions refactor is in.
