### ISSUE TITLE
Look into `--html` preceding `--ghmarkdown`

### ISSUE THREAD

**Issue by IvanUkhov** [fonttools/fontbakery#4514]
Hello,

With Font Bakery 0.11+, we are seeing that the ordering of reporter arguments matters. If `--html` is given first, `--ghmarkdown` does not produce any output. If the order is flipped, both file types appear.

**Comment by simoncozens** [comment]
It seems OK *now*, once #4523 is applied.

**Comment by simoncozens** [comment]
Fixed!
