### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by panosvassiliou** [fonttools/fontbakery#4519]
FontBakery.com returns an error after you upload a font and press the bake button 

![Screenshot 2024-02-15 at 12 04 30 AM](https://github.com/fonttools/fontbakery/assets/72914151/2cc3b629-e2c4-4fc0-82fc-edb8af63cf44)

**Comment by simoncozens** [comment]
Yes, I need to fix it again after the recent refactor, sorry.

**Comment by simoncozens** [comment]
Fixed it.

**Comment by panosvassiliou** [comment]
Great, thanks for the swift fix!

**Comment by panosvassiliou** [comment]
Hi Simon,

There is an issue with the Type Network profile online (see attachment)

thanks,
Panos


Panos Vassiliou
Director / Head of Creative

PARACHUTE
GR 14 Taki Street, Athens 10554 GR
UK 71-75 Shelton Street, London WC2H 9JQ United Kingdom
T +30 210 8018100
***@***.*** ***@***.***> 
www.parachutefonts.com <http://www.parachutefonts.com/>
www.typeroom.eu <http://www.typeroom.eu/>
www.letteres.com <https://letteres.com/>
￼
