### ISSUE TITLE
[com.google.fonts/check/smart_dropout] FAILs when all checks run, PASSes when only this check runs

### ISSUE THREAD

**Issue by yanone** [fonttools/fontbakery#4525]
Check fails on [this font](https://github.com/google/fonts/pull/7208/files#diff-122535ad6a9ca3be7d0dc01d1a8e1314b674908514a4b14a63e5bb89853b1a90) in the CI and when I run Fontbakery locally, but passes when I run just that one check using `-c smart_dropout`.

I investigated the font and the code think it should pass in any case, so I'm very much at a loss of ideas what could cause this behaviour. It seems to be some sort of interference with other checks running.

**Comment by simoncozens** [comment]
Confirmed, I'm taking a look.
