### ISSUE TITLE
[com.google.fonts/check/unreachable_glyphs] Glyphs reached from MATH table are reported as unreacable

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fontbakery#4536]
## Observed behaviour

A font with `MATH` table will report many glyphs that reached from `MATH` table as unreachable.

## Expected behaviour

It should take `MATH` table into account.

## Resources and steps needed to reproduce

Using [`NotoSansMath-Regular.otf`](https://notofonts.github.io/math/fonts/NotoSansMath/full/ttf/NotoSansMath-Regular.ttf), gives:

</div></details><details><summary>⚠ <b>WARN:</b> Check font contains no unreachable glyphs (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/unreachable_glyphs">com.google.fonts/check/unreachable_glyphs</a>)</summary><div>

>
>Glyphs are either accessible directly through Unicode codepoints or through substitution rules.
>
>In Color Fonts, glyphs are also referenced by the COLR table.
>
>Any glyphs not accessible by either of these means are redundant and serve only to increase the font's file size.
>
* ⚠ **WARN** The following glyphs could not be reached by codepoint or substitution rules:

	- arrowdblup.x

	- arrowleft.l

	- arrowright.r

	- arrowup.x

	- backslash.s1

	- backslash.s2

	- backslash.s3

	- backslash.s4

	- braceleft.s1

	- braceleft.s10

	- 475 more.

Use -F or --full-lists to disable shortening of long lists.
 [code: unreachable-glyphs]

**Comment by felipesanches** [comment]
thanks

**Comment by felipesanches** [comment]
After making the check aware of the references in the MATH table, I still get one unreachable glyph (**upWhiteMediumTriangle**):

![Screenshot from 2024-02-20 06-12-48](https://github.com/fonttools/fontbakery/assets/213676/4a9b6e23-ee1d-4ed1-bb53-aad4fab92020)

@khaledhosny do you know where this glyph is supposed to be referenced / used? Or would this be a legitimate font bug detected by the check?

**Comment by khaledhosny** [comment]
`upWhiteMediumTriangle` is used as a component in `circledTriangle`, since CFF does not have composites it became unused. So that is a build tooling issue.
