### ISSUE TITLE
`check_arabic_high_hamza` always SKIPs

### ISSUE THREAD

**Issue by bobh0303** [fonttools/fontbakery#4539]
I may be misunderstanding, but it looks to me as if this code:

https://github.com/fonttools/fontbakery/blob/033a59ef84f267a4f13230258fb2c522dd3d037c/Lib/fontbakery/checks/universal/__init__.py#L913-L920

always produces a SKIP since, according to [fontTools documentation](https://fonttools.readthedocs.io/en/latest/ttLib/ttFont.html#fontTools.ttLib.ttFont.TTFont.getGlyphSet), `ttFont.getGlyphSet()` returns 

>a dict-like object mapping glyph names to glyph objects

— it is not keyed by USV.  

While on the subject, it may be unusual for a font to have ARABIC_LETTER_HIGH_HAMZA but _not_ have ARABIC_LETTER_HAMZA, but in the case some such font comes along it seems this check should still test that ARABIC_LETTER_HIGH_HAMZA isn't a mark even if it can't test the approximate glyph size. Therefore I suggest the above SKIP happen only if ARABIC_LETTER_HIGH_HAMZA is absent. The presence/absence of ARABIC_LETTER_HIGH_HAMZA should then enable/disable the 2nd part of the check.

**Comment by simoncozens** [comment]
`ARABIC_LETTER_HAMZA not in glyph_set or ARABIC_LETTER_HAMZA not in glyph_set`

is clearly wrong anyway.
