### ISSUE TITLE
HTML output: Add issue links, MD: fix docs link

### ISSUE THREAD

**Issue by yanone** [fonttools/fontbakery#4540]
The CLI output contains links to the issues that lead to the creation of each check under "More info:"

Both the HTML output as well as the MD output are missing this, which is a bummer if I want to send an HTML report to a font author, where they could dig into issues to understand problems and solutions.

The MD at least contains links to the docs for each issue, but these are also broken, so that doesn't help either.

**Comment by felipesanches** [comment]
Here we still need to add links to "More info:"
