### ISSUE TITLE
`check-profile` gives RuntimeWarning

### ISSUE THREAD

**Issue by bobh0303** [fonttools/fontbakery#4562]
## Observed behaviour

```
> fontbakery check-profile -h
/usr/lib/python3.10/runpy.py:126: RuntimeWarning: 'fontbakery.commands.check_profile' found 
in sys.modules after import of package 'fontbakery.commands', but prior to execution of 
'fontbakery.commands.check_profile'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
usage: fontbakery check-profile [-h] [--configuration CONFIGFILE] [-c CHECKID] [-x EXCLUDE_CHECKID] [-v] [-q]
...
```

## Expected behaviour

RuntimeWarning shouldn't be displayed

## Resources and steps needed to reproduce

Python version: 3.10.12

Fontbakery version: I get the same result with two different versions:

- 0.11.2
- Running from source installed in edit mode from repo at commit 05900ff3. Installation steps I used:
```
> sudo pip3 uninstall fontbakery
> git clone https://github.com/fonttools/fontbakery
> cd fontbakery
> sudo pip3 install --upgrade -e . --verbose --use-pep517
```

**Comment by simoncozens** [comment]
`cli.py` and `check_profile.py` are, at this point, doing the same thing and should be merged, that will fix this.
