### ISSUE TITLE
`List all checks` button doesn't work

### ISSUE THREAD

**Issue by justinpenner** [fonttools/fontbakery#4566]
## Observed behaviour

<img width="972" alt="image" src="https://github.com/fonttools/fontbakery/assets/46039243/307adf97-d164-4eef-889e-5f08cccb5a4f">

## Expected behaviour

A list of all checks for the currently selected profile.

## Resources and steps needed to reproduce

Click the `List all checks` button at the bottom of fontbakery.com. Doesn't seem browser-related, as I'm getting the same error in Chrome/Firefox/Safari on Monterey 12.6.5.

cc @simoncozens

**Comment by simoncozens** [comment]
Working on it.
