### ISSUE TITLE
HTML and Markdown reporters are broken

### ISSUE THREAD

**Issue by guidoferreyra** [fonttools/fontbakery#4595]
The original title of this issue was: "HTML reporter is broken for FAIL results"
----

## Observed behaviour
All the FAIL checks are being being ommited on the HTML report.  See image.

![imagen](https://github.com/fonttools/fontbakery/assets/1755590/1f2789c6-2d5b-49d5-a8aa-f089173b6ca0)

Other checks that produces WARNS or ERROR are displayed correctly

**Comment by glenda-tn** [comment]
This is also broken for WARNS.

**Comment by m4rc1e** [comment]
Broken all round I'm afraid, https://github.com/google/fonts/pull/7384#issuecomment-1999294850

**Comment by felipesanches** [comment]
Ouch! Sorry for that!

I'll try to fix it as quickly as possible

**Comment by guidoferreyra** [comment]
On my local clone of the repo I still don’t see the FAILS 🤔
