### ISSUE TITLE
Idea: PASS should be the default if not return value

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4612]
## Observed behaviour

I'm sick of this pattern:

```python
    ok = True
    if this_is_bad:
        ok = False
        yield FAIL, Message("this-bad", "A bad thing happened")
    if that_is_bad:
        ok = False
        yield FAIL, Message("this-bad", "A bad thing happened")

    if ok:
        yield PASS, "All is well"
```   

## Expected behaviour

The check runner should assume all is well if it doesn't hear otherwise.

**Comment by felipesanches** [comment]
I agree. I've considered this in the past. Since you're describing precisely the same idea, it seems it is a good thing to do. I'll implement this today.
