### ISSUE TITLE
[webversion] TypeNetwork Profile broken

### ISSUE THREAD

**Issue by moritz-kleinsorge** [fonttools/fontbakery#4616]
The TypeNetwork Profile is broken in the web version.

@guidoferreyra 
@simoncozens 

<img width="994" alt="Bildschirmfoto 2024-03-26 um 22 41 05" src="https://github.com/fonttools/fontbakery/assets/65606571/dafe08d2-bd28-4e89-8ec6-d5e1695b6f1a">

**Comment by guidoferreyra** [comment]
Yes, AFAIK this will fixed with the release of v0.12. @felipesanches any estimated time for this release?

**Comment by felipesanches** [comment]
I've cut a new pre-release today. It seems to be working properly now

**Comment by guidoferreyra** [comment]
THANKS!
