### ISSUE TITLE
The exit code is always 0 regardless if there are failures or not

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fontbakery#4633]
## Observed behaviour

The exist code is always zero, regardless if there are failing checks or if `-e` is used. 

## Expected behaviour

There error code should be non-zero if there failing checks (or the level set with `-e`)

**Comment by khaledhosny** [comment]
This appears to happen only when called as `python -m fontbakery`, should be fixed with #4634.

**Comment by felipesanches** [comment]
thanks!
