### ISSUE TITLE
Problem with fontbakery.com

### ISSUE THREAD

**Issue by schriftgestalt** [fonttools/fontbakery#4639]
When I open fontbakery.com, after a few seconds I get this: 

```
Traceback (most recent call last):
  File "/lib/python311.zip/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 1209, in _gcd_import
  File "", line 1181, in _find_and_load
  File "", line 1152, in _find_and_load_unlocked
  File "", line 690, in _load_unlocked
  File "", line 940, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "/home/pyodide/fbwebapi.py", line 33, in 
    import glyphsets
  File "/lib/python3.11/site-packages/glyphsets/__init__.py", line 34, in 
    assert type(GLYPHDATA) is glyphsLib.glyphdata.GlyphData
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by guidoferreyra** [comment]
Same here.

**Comment by yanone** [comment]
@felipesanches This code got introduced way back when I startet revamping glyphsets, so pinning it to 0.6.17 doesn't even help. (And also the error persists on fontbakery.com)

In any case, this code was a workaround for GLYPHDATA in glyphsLib not properly loading unless a get_glyph() command was issued first. I removed the lines now and glyphsets own CI passes. Do you have a way to test the repo code in fontbakery.com before me releasing a new package? Can you link to the repo directly?

**Comment by felipesanches** [comment]
I'm afraid we don't have an easy way of testing fontbakery.com with a dependency installed from a git repo. Maybe @simoncozens knows some way of doing it?

**Comment by simoncozens** [comment]
Yep, we can check out the gh-pages branch locally and change the pip commands. I'll have a go later.

**Comment by felipesanches** [comment]
great, thanks!

**Comment by simoncozens** [comment]
I can confirm the git version works fine. (It wasn't as simple as pointing micropip at the repo, because it doesn't support loading packages from git - I had to build a wheel and copy that into the gh-pages directory and then have it load that. But hey, it works.)

@yanone I would consider removing all those commented out lines; `GLYPHDATA` doesn't seem to be used in glyphsets at all.

**Comment by felipesanches** [comment]
thanks, @simoncozens 

@yanone, I'll update `pyproject.toml` to unpin glyphsets once we get a new version of it released

**Comment by guidoferreyra** [comment]
TN profile is failing now and it shows the following:
![imagen](https://github.com/fonttools/fontbakery/assets/1755590/125fcf39-8ca4-4e0d-babf-818285d7fdee)

I’m not getting that error either on the latest commit nor latest stable release (0.12.1)

**Comment by felipesanches** [comment]
> TN profile is failing now and it shows the following: ![imagen](https://private-user-images.githubusercontent.com/1755590/323321779-125fcf39-8ca4-4e0d-babf-818285d7fdee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzgxNzcsIm5iZiI6MTcxMzM3Nzg3NywicGF0aCI6Ii8xNzU1NTkwLzMyMzMyMTc3OS0xMjVmY2YzOS04Y2E0LTRlMGQtYmFiZi04MTgyODVkN2ZkZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMTgxNzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTgyNGZjNjU5M2MxOWVhZWNiMmMzNzY2OWQzZWQ4MjI1NDI4ZDZjNjY5NWNlNjBjNDA2ZTcxMTg2YzM3MDNkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PnwcBvpEyOOluBBDIPUUvf9ZGO-VJwlp5t-dSeLypmA)
> 
> I’m not getting that error either on the latest commit nor latest stable release (0.12.1)

Are you running the web-version via a checkout of gh-pages locally on your computer?

Or is it a screenshot of the publicly deployed fontbakery.com?

**Comment by felipesanches** [comment]
I've just released FontBakery v0.12.2 and fontbakery.com seems to be working nicely. But I will leave this issue open for a while, to discuss @guidoferreyra's problem which sounds to me like a broken dependency resolution on his local environment.

**Comment by guidoferreyra** [comment]
> Are you running the web-version via a checkout of gh-pages locally on your computer?
> 
> Or is it a screenshot of the publicly deployed fontbakery.com?

Sorry I didn‘t add much context, that’s screenshot is from Fontbakery.com.

Web version is working for other profiles, but if you select TN‘s drop a font and wait a bit you will see the error message.

**Comment by guidoferreyra** [comment]
Now I see it only happens with one specific font. Unfortunately I can‘t share that font. Anyway I gues this is fixed, I will keep an eye in case the error is raised for another font.

**Comment by felipesanches** [comment]
thanks!
