### ISSUE TITLE
[com.google.fonts/check/glyphsets/shape_languages] output contains unnecessary messages triggered by already-reported problems

### ISSUE THREAD

**Issue by bobh0303** [fonttools/fontbakery#4654]
Once "Missing glyph" [technically this is a missing "character" as it was missing from the cmap] errors are reported, there is no need to report other errors related to the same character, such as missing contextual forms or attachments not working.

## Observed behaviour

```
           fa_Arab (Persian)   Some base glyphs were missing: چ
           ^                   Shaper produced a .notdef
           ^                   .fina version of ARABIC LETTER TCHEH; both buffers returned .notdef=1+1033
           ^                   Shaper didn't attach uni064B to None
           ^                   Shaper didn't attach uni064D to None
           ^                   Shaper didn't attach uni064C to None
           ^                   Shaper didn't attach uni0651 to None
           ^                   Shaper didn't attach uni0654 to None
           ^                   .medi version of ARABIC LETTER TCHEH; both buffers returned space=1+0
           ^                   Shaper didn't attach uni064B to space
           ^                   Shaper didn't attach uni064D to space
           ^                   Shaper didn't attach uni064C to space
           ^                   Shaper didn't attach uni0651 to space
           ^                   Shaper didn't attach uni0654 to space
           ^                   .init version of ARABIC LETTER TCHEH; both buffers returned space=0+0
```

## Expected behaviour

All of the above messages are a result of the font not encoding U+0686 ARABIC LETTER TCHEH so the first message is all that is needed:

```
           fa_Arab (Persian)   Some base glyphs were missing: چ
```

## Resources and steps needed to reproduce

font: Alkalami v3.000, downloadable from
https://software.sil.org/alkalami/download/

```
fontbakery check-googlefonts -c com.google.fonts/check/glyphsets/shape_languages Alkalami-Regular.ttf | more
```
fontbakery from source at tag v0.12.2
python 3.10.12
ubuntu 22.04

**Comment by bobh0303** [comment]
(I realize this one might be harder to clean up than #4646)

**Comment by felipesanches** [comment]
"Shaper didn't attach uni064B to None" sounds non-sensical. Perhaps we should address that first.

**Comment by bobh0303** [comment]
> "Shaper didn't attach uni064B to None" sounds non-sensical. Perhaps we should address that first.

I assume that was because the test attempted to attach the mark to the missing/unencoded base char [that was previously reported] and got glyph #0 / .notdef which some part of the rendering stack or reporting logic mapped that to "None".

**Comment by simoncozens** [comment]
This is probably an issue that belongs in the shaperglot repository.
