### ISSUE TITLE
[web] com.google.fonts/check/ttx_roundtrip throws ERROR

### ISSUE THREAD

**Issue by guidoferreyra** [fonttools/fontbakery#4661]
IRRC this check worked on the web environment, right? I noticed in the last version is throwing the following error:
```
ERROR :

Failed with OSError: [Errno 138] emscripten does not support processes.

  File "/lib/python3.11/site-packages/fontbakery/checkrunner.py", line 213, in _run_check
    subresults = list(subresults)
                 ^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontbakery/checks/universal/__init__.py", line 1369, in com_google_fonts_check_ttx_roundtrip
    export_process = subprocess.Popen(
                     ^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/subprocess.py", line 818, in __init__
    raise OSError(

```

**Comment by felipesanches** [comment]
That's right! The check was simplified by employing the subprocess module, but emscripten does not support that.

It may be the case of knowing the limitations of the web-version and living with that.

But it also prompts my nerdy-brain to question: why isn't that supported? I guess the answer may be very simple, but I am not sure. Is there official emscripten documentation describing and justifying each of its limitations?

**Comment by felipesanches** [comment]
My perspective is that the web version is an interesting feature, and may be useful for some people, but it does not replace running the full version of fontbakery, either via the command line or via github actions or similar continuous integration deployments.

With that in mind, I think it is not worth it to spend too much effort improving the web version.

**Comment by felipesanches** [comment]
No, I'd rather keep it as it is now. Making this SKIP would hide that informative message. And I fear that people may not be aware that the web version is incomplete.
