### ISSUE TITLE
[com.google.fonts/check/fvar_instances] Table formatting is off

### ISSUE THREAD

**Issue by yanone** [fonttools/fontbakery#4675]
![Bildschirmfoto 2024-04-25 um 15 52 22](https://github.com/fonttools/fontbakery/assets/175386/74d4a472-3974-434b-a032-e86f2c0f3453)

Try with this font: 
[Bitter-Italic[wght].ttf.zip](https://github.com/fonttools/fontbakery/files/15111108/Bitter-Italic.wght.ttf.zip)

**Comment by felipesanches** [comment]
Thanks. I'll fix this now.
