### ISSUE TITLE
[com.google.fonts/check/caret_slope] Downgrade to WARN

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4679]
## Observed behaviour

We currently FAIL if the caret slope rise and run values are wrong for italic glyphs. But according to @vv-monsalve, no applications these days display a slanted cursor caret!

## Expected behaviour

We shouldn't FAIL for non-problems.

**Comment by felipesanches** [comment]
If it is not a real problem, should we then deprecate the check?

Or would you prefer to keep it as a WARN? Any hope this will someday be supported at all?

**Comment by kenmcd** [comment]
It appears that some applications still support it.
![Slanted Cursor in Word 2024](https://github.com/fonttools/fontbakery/assets/844920/43b24a81-532d-4dda-b3dd-5adce83edade)

**Comment by vv-monsalve** [comment]
After the latest tests I performed, it's not in use on Adobe apps, Pages, Libre Office in macOS. 
Only Word seemed to be working ok with them.

@kenmcd what OS and app versions are these?

**Comment by vv-monsalve** [comment]
> Or would you prefer to keep it as a WARN? Any hope this will someday be supported at all?

I would keep it as a WARN. Caret values are part of the hhea table from the OT spec, so they _should_ be supported. However, multiple apps seem not to be using them to represent a slanted cursor.

**Comment by kenmcd** [comment]
> @kenmcd what OS and app versions are these?

Word Office 2024 Preview on Windows 11 Pro 23H2
Microsoft® Word LTSC MSO (Version 2403 Build 16.0.17425.20176) 64-bit 

Word Office 2019 on Windows 10 Pro 22H2
Microsoft® Word 2019 MSO (Version 2402 Build 16.0.17311.20000) 64-bit 
I installed 2021 over 2019 and this is what it still says.

Affinity Publisher 2.4.1 on Windows 10 Pro 22H2
