### ISSUE TITLE
[com.google.fonts/check/outline_direction] failed with `ZeroDivisionError`: float division by zero  

### ISSUE THREAD

**Issue by RickyDaMa** [fonttools/fontbakery#4699]
## Observed behaviour

The check errors:

![image](https://github.com/fonttools/fontbakery/assets/113340856/5c22d143-0c49-4109-8bfa-767bd8bb1eaf)

## Expected behaviour

The check should fail (I think). I'm guessing this exception should be caught and repackaged as the check failing?

## Resources and steps needed to reproduce

I'll link this issue on the private repo in question, so you'll see the backlink below if you have access :)

**Comment by simoncozens** [comment]
It's clearly in beziers.py. You won't find a length-zero bezier in your sources; it's probably a bug in how we're sampling them.

**Comment by simoncozens** [comment]
Should be fixed in beziers 0.6.0, just uploaded.

**Comment by felipesanches** [comment]
> Should be fixed in beziers 0.6.0, just uploaded.

Even though I see version 0.6.0 at PyPI (https://pypi.org/project/beziers/), I don't see the corresponding commits / git tag for this version at https://github.com/simoncozens/beziers.py

**Comment by simoncozens** [comment]
This should now be fixed.
