### ISSUE TITLE
[com.google.fonts/check/article/images] should pass if there is not an `article/images` dir

### ISSUE THREAD

**Issue by vv-monsalve** [fonttools/fontbakery#4703]
## Observed behavior

> ⚠️ WARN
> There are 3 image files in the article directory and they should be moved to an article/images subdirectory:

The above Warn was reported on this [CI run](https://github.com/google/fonts/pull/7639#issuecomment-2101209174). However, in [this comment ](https://github.com/fonttools/fontbakery/issues/4594#issuecomment-2014012291)on the issue proposal for a new check, Nathan Williams said the `images` subdirectory is not required.

## Expected behavior

The check should pass if there is no `images` subdirectory under the `article` one (not reporting a Warn).

## Resources and steps needed to reproduce

See CI run linked above

**Comment by felipesanches** [comment]
It is just a WARN... for the sake of moving the repo towards some more homogeneous structure.

* How many outliers do we actually have?
* How hard would it be to reorganize the entire repo at once, moving all images to their respective `images` sub-dirs and afterwards making it mandatory?

I'd say there's some benefit for tooling and for user-friendliness to have a more regular directory structure.

**Comment by felipesanches** [comment]
> It is just a WARN... for the sake of moving the repo towards some more homogeneous structure.
> 
>     * How many outliers do we actually have?
> 
>     * How hard would it be to reorganize the entire repo at once, moving all images to their respective `images` sub-dirs and afterwards making it mandatory?
> 
> 
> I'd say there's some benefit for tooling and for user-friendliness to have a more regular directory structure.

@nathan-williams, I'd be glad to hear your thoughts here as well. What do you think?

**Comment by vv-monsalve** [comment]
> * How many outliers do we actually have?

We are not currently using an "images" folder, so having it would be kind of the _outlier_

> How hard would it be to reorganize the entire repo at once

It would require changing the paths in multiple HTML article files, which would be time-consuming on something that is not a strong requirement or need.

**Comment by emmamarichal** [comment]
@vv-monsalve I agree. I've never seen a sub-dir called "images". What would that include, having another sub-folder for GIFS? videos? 
I think we'd be complicating the process and it would actually require too many changes for something that I think works very well.

**Comment by felipesanches** [comment]
ok, no worries. I'll make the proposed change, then.
