### ISSUE TITLE
Old versions of Jinja cause errors

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fontbakery#4717]
## Observed behavior

Running Font Bakery with a version of Jinja before version 3.0.0 raises an error: `ImportError: cannot import name 'soft_unicode' from 'markupsafe'`.

## Expected behavior

Font Bakery’s pyproject.toml should restrict the dependency to versions that work: `Jinja2 >= 3.0.0`.

## Resources and steps needed to reproduce

```zsh
pip install Jinja2==2.11.3 fontbakery==0.12.6
fontbakery
```

**Comment by felipesanches** [comment]
Please, send a PR with this proposed fix.
