### ISSUE TITLE
Old versions of Requests cause errors

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fontbakery#4718]
## Observed behavior

Running Font Bakery with an old version of Requests raises an error. Version 2.19 is the oldest that works with all versions of Python that Font Bakery supports.

## Expected behavior

Font Bakery’s pyproject.toml should restrict the dependency to versions that always work: `requests >= 2.19`. (This could be made more precise with environment markers, since some older Requests versions work in some older Python versions.)

## Resources and steps needed to reproduce

```zsh
pip install requests==0.2.0 fontbakery==0.12.6
touch placeholder.otf
fontbakery check-universal -c com.google.fonts/check/fontbakery_version placeholder.otf
```

**Comment by felipesanches** [comment]
Please, send a PR with this proposed fix.
