### ISSUE TITLE
New check: Metadata has valid date

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4729]
## What needs to be checked?

If date_added is empty or malformed, things Get Bad. We should check that. Probably not as a self-contained check, but as part of something else that is checking METADATA.pb

## Suggested profile

Suggest which profile the check should be added to. The most common are:

- [X] Vendor-specific: Google Fonts
- [ ] Vendor-specific: Adobe Fonts
- [ ] OpenType (requirements imposed by the OpenType specification)
- [ ] Universal (broadly accepted best practices on the type design community)
- [ ] Other:

## Suggested result

Which log result level should the check have:

- [X] 🔥 **FAIL** (An issue that must be corrected for the font to function properly)
- [ ] ⚠️ **WARN** (A potential issues that may need to be addressed)

## Severity assessment

5, causes servers to fail.

**Comment by felipesanches** [comment]
This kind of problem happened recently in this case: https://github.com/google/fonts/pull/7694/files

**Comment by felipesanches** [comment]
I'm assuming here that the only acceptable format is **YYYY-MM-DD**

**Comment by felipesanches** [comment]
Even though you suggested adding this validation to some preexisting check, I opted here to create a new check because I think we should address separately and more carefully that matter of organization of (and an eventual clumping of) checks.

**Comment by vv-monsalve** [comment]
This had broken the push to dev, so the status for this should be ☠️ **FATAL**

**Comment by felipesanches** [comment]
Yes, @simoncozens had proposed FAIL but I actually made it FATAL.

**Comment by felipesanches** [comment]
https://github.com/fonttools/fontbakery/blob/687e6fa1948910b5ba4cc612e8efc4f43faf0e5d/Lib/fontbakery/checks/googlefonts/metadata.py#L84-L85

https://github.com/fonttools/fontbakery/blob/687e6fa1948910b5ba4cc612e8efc4f43faf0e5d/Lib/fontbakery/checks/googlefonts/metadata.py#L102-L106
