### ISSUE TITLE
[com.google.fonts/check/case_mapping] getting FAILs on unimportant glyphs

### ISSUE THREAD

**Issue by RickyDaMa** [fonttools/fontbakery#4733]
## Observed behaviour

![image](https://github.com/fonttools/fontbakery/assets/113340856/287078af-f66f-4e09-8b17-9dd0bbac164e)

## Expected behaviour

It would be nice if some glyphs (like Roman numerals for example) were considered less important and perhaps only WARNed instead of failing

Even better would be being able to exclude some glyphs from the check, since in this case we have no intention on adding `U+24D6`

For now we've overriden the entire check to WARN instead of FAIL, but some more granular control here might be worth considering

## Resources and steps needed to reproduce

Fontbakery 0.12.6

Backlink will be visible below to those with access :)

**Comment by dscorbett** [comment]
This check could ignore [non-letters that casing changes](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%5B%3AChanges_When_Lowercased%3A%5D%5B%3AChanges_When_Uppercased%3A%5D%5D-%5B%3AL%3A%5D&g=&i=).
