### ISSUE TITLE
New check: Metadata invalid minisite_url

### ISSUE THREAD

**Issue by vv-monsalve** [fonttools/fontbakery#4739]
## What needs to be checked?

If minisite_url has a random text instead an `http://` + `domain` string the push to dev gets broken.

## Resources and steps needed to reproduce the problem

(Provide the steps and files for reproducing the problem. We will need them for developing the proposed check and for including them in tests that validate the codebase)

## Suggested profile

Suggest which profile the check should be added to. The most common are:

- [x] Vendor-specific: Google Fonts
- [ ] Vendor-specific: Adobe Fonts
- [ ] OpenType (requirements imposed by the OpenType specification)
- [ ] Universal (broadly accepted best practices on the type design community)
- [ ] Other:

## Suggested result

Which log result level should the check have:

- [x] ☠️ **FATAL** 
- [ ] 🔥 **FAIL** (An issue that must be corrected for the font to function properly)
- [ ] ⚠️ **WARN** (A potential issues that may need to be addressed)

## Severity assessment

5, causes servers to fail.

**Comment by vv-monsalve** [comment]
This happened here https://github.com/google/fonts/pull/7762/files

**Comment by felipesanches** [comment]
we already have **com.google.fonts/check/metadata/minisite_url**, but it only alerted us when decluttering was needed (such as removing extra white-space). I'll add a URL check to see if the url is not broken, Similar to other URL checks, if it doesn't return a 404 HTTP error code, then it means it is a good URL.

**Comment by felipesanches** [comment]
My understanding is that this is already implemented.
