### ISSUE TITLE
[com.google.fonts/check/outline_direction] Contradictory wording

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fontbakery#4743]
In the changelog, the check is summarized as "Check that outermost contours of glyphs have a **clockwise** direction".

The rationale of the check says "In TrueType fonts, the outermost contour of a glyph should be oriented **counter-clockwise**".

When I run the check, it gives me a WARN e.g. "O (U+004F) has a **counter-clockwise** outer contour" when actually the outer contour of O is **clockwise.**

This is all very confusing. The contour is clockwise as it should be.

**Comment by jenskutilek** [comment]
The WARN on my font probably resulted from a bug that was fixed in #4719; with the current dev version, the check passes. So I think it's just the wording in the rationale and message itself that is wrong.

**Comment by felipesanches** [comment]
thanks!
