### ISSUE TITLE
Request for feedback: Proposal of reorganization of profiles

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4801]
Currently we have these profiles:

* adobefonts
* fontbureau
* fontval
* fontwerk
* googlefonts
* iso15008
* microsoft
* notofonts
* opentype
* outline
* shaping
* typenetwork
* ufo
* universal

We can categorize them this way:

# Generaly useful ones:
* Universal - Universally adopted QA criteria.
* OpenType - Things required by the spec
* iso15008 - Another industry standard, but not necessarily used by everyone.

# Vendor specific profiles:
* adobefonts
* fontbureau
* fontwerk
* googlefonts
* microsoft
* typenetwork

# Profile defined by file-type:
* ufo - checks for Unified Font Object files.

# Profiles defined by aspect of problems being checked for:
* outline - Glyph outline characteristics
* shaping - Problems related to font shaping.

# outliers:
* fontval - a wrapper around a 3rd party QA tool (originally what one could call the "Microsoft" profile)
* notofonts - project-specific QA criteria (sort of "GoogleFonts" profile)

----

I think that we should reorganize the profiles to be categorized strictly by vendor needs. It means that we should fit everything into either "Generaly useful profiles" or "Vendor specific profiles".

So, for instance, UFO checks should be assigned to either vendor-specific profiles or to the Universal one.
Same reasoning for shaping and outline.

Maybe we should drop support for fontval. Or, maybe, the check could be included in the Microsoft profile.

I think it won't be too hard to include notofonts related checks in the GoogleFonts profile and simply check Noto families with the GFonts profile.

The only one here that I am still a bit uncertain is the **iso15008** one. Not sure if we should have a special way to enable/disable that kind of profile, as it definitely does not apply to all font families (so it can't be considered universal), but it is also not vendor-specific. This one sounds legitimately optional.

**Comment by davelab6** [comment]
Broadly I support this work

**Comment by felipesanches** [comment]
OK... `UFO`, `Shaping` and `Outline` profiles are gone, via #4812 

Now what to do about the rest?

I think I'll treat `NotoFonts` as a special kind of vendor. And I'll probably deprecate `Fontval` profile and move the check to `Universal`, while making it optional (simply bail out if **FontValidator** is not found, or maybe add an `opt-in` flag?)
