### ISSUE TITLE
[com.google.fonts/check/gsub/smallcaps_before_ligatures] should yield SKIP if there are no SC features

### ISSUE THREAD

**Issue by fridamedrano** [fonttools/fontbakery#4804]
## Observed behaviour

Testing a font that has no small caps at all, the check gives a FAIL:

```
FAIL 'smcp' or 'liga' lookups not found in GSUB table. [code: missing-lookups]                                                                                    
```

## Expected behaviour

It should yield SKIP.

## Resources and steps needed to reproduce

fontbakery 0.12.8
[Mesoa-Bold.ttf.zip](https://github.com/user-attachments/files/16405205/Mesoa-Bold.ttf.zip)

**Comment by felipesanches** [comment]
This was already fixed on FontBakery version 0.12.9. Please update your installation.
