### ISSUE TITLE
Drop reverse domain in check IDs

### ISSUE THREAD

**Issue by felipesanches** [fonttools/fontbakery#4817]
For many years we've been using check IDs with the format **`<reverse-domain>`/check/`<keywords>`**. With the reverse domain indicating the main contributor of each check. We currently have these 9 domains in the repo:

* com.adobe.fonts
* com.arrowtype.fonts
* com.daltonmaag
* com.fontwerk
* com.google.fonts
* com.microsoft
* com.thetypefounders
* com.typenetwork
* io.github.abysstypeco

We've had reports from users getting confused about the meaning of these reverse domains. Some users think that these can indicate a profile, but that's not true. As these domains are not really that much useful and, as in the spirit of a free software project, checks are frequently updated with contributions from multiple organizations, I believe that we should abandon this practice.

I have suggested changing all check IDs to **com.fontbakery/check/`<some_keywords>`** but @simoncozens proposed completely removing the reverse domains and the "/check/" part.

My reasoning for keeping them was that it makes it very clear that we're talking about a FontBakery check ID, while **bare_keywords** may not so clearly convey that idea and we would have to rely on the context of a sentence (such as in the body of a bug report). 

Also, I wanted to keep "/check/" because there's hope to support other kinds of objects, such as auto-fixers, in FontBakery as well (and some prototypes are being drafted at https://github.com/simoncozens/fontspector/). But Simon has a good point when he argues that all other objects would simply cross-reference some check, by using its check-id (such as in "`this fixer` is meant to fix the problems detected by `that check`")

**Comment by felipesanches** [comment]
Even though it was always possible to have check-ID clashes when ignoring the reverse domain names, now I have inspected the current code-base and luckily I did not find any such case among the 337 existing checks.

But I did find some very generic short names that concern me. We'll maybe have some trouble with IDs such as "copyright" which could have completely different vendor-specific implementations. I think that would be a reason to still keep the reverse domain names.

One idea would be to almost always use "com.fontbakery/check", except when one is pretty sure that an implementation is strictly vendor-specific.

**Comment by felipesanches** [comment]
Recent refactoring placed all checks in a common pool (the **Lib/fontbakery/checks/** directory), before they are selected in the description of each profile (the files under **Lib/fontbakery/profiles/**).

I believe that this redesign of check-ID nomenclature may also be beneficial in terms of more strongly signaling a general project goal of strengthening a common set of checks. Making an effort to migrate as many checks as possible to `Universal` profile.

**Comment by felipesanches** [comment]
It may also make it easier to sort check IDs alphabetically by their keywords keeping them visually aligned while not violating black formatting rules. (This one may be just a cosmetic detail, but it is something that annoys me a bit)

**Comment by felipesanches** [comment]
Since there are many ideas in this issue, I think the best approach would be for me to open a branch and make the changes I consider necessary & useful, and then ask for comments from anyone else interested.

This is the kind of change that may break users' setup, so it would require careful thought and would also require releasing it as a version bump (probably FB v0.13.0, but I can skip straight to v0.14.0 if people prefer to avoid the number 13! :-P).

It will also require a short-guide (or simply a very prominent CHANGELOG entry, perhaps!?) with instructions to users on how to update their setup. It should not be too hard, I think.

**Comment by felipesanches** [comment]
> 2. Remove the reverse domains from all check IDs, but then append (or prefix) vendor names to the check IDs. So, these check IDs would become something like googlefonts:font_copyright and microsoft:font_copyright

I'm right now drafting option number 2 on a branch, that I'll make public later today.

**Comment by simoncozens** [comment]
> 3. Anybody has got any other idea?

`googlefonts:font_copyright` and `microsoft:font_copyright` is okay, because GF and MS have different standards about what the copyright should be. But to me it just suggests that the check ID is not well named. The GF case is looking for a particular copyright pattern, so that's not very generically applicable, but `com.microsoft/check/copyright` is not Microsoft specific-and could become `name_0_copyright_not_empty`.

**Comment by simoncozens** [comment]
Afterthought: This is a sensitive one, because we want to be able to give third-party vendors the ownership and the space to choose their own check names without us coming in and rewriting everything, but at the same time I would like generically applicable checks to belong to the whole "commons" of Fontbakery. So I think, in the future, when reviewing new check PRs we ask "Does this check hold to a specific vendor standard which is not generally applicable to others?" If so, when reviewing, we ensure that it gets a generic but descriptive name; if it is not generically applicable, then namespace it with `vendor:` and do whatever you want.
