### ISSUE TITLE
[Vertical Metrics] 💥 ERROR: 'manifest'

### ISSUE THREAD

**Issue by emmamarichal** [fonttools/fontbakery#4823]
[Vertical Metrics] 💥 ERROR: 'manifest'

@felipesanches @m4rc1e

## Observed behaviour

Hi! I have these two errors, they seem to be a bug!
_Edit:_ I just tested with [v0.12.9](https://github.com/fonttools/fontbakery/releases/tag/v0.12.9), and I don't have these ERRORS.

<div>
<details>
    <summary>💥 <b>ERROR</b> Check if the vertical metrics of a CJK family are similar to the same family hosted on Google Fonts. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/googlefonts.vmetrics.html#"></a></summary>
    <div>

* 💥 **ERROR** <p>'manifest'</p>
 [code: error]

</div>
</details>

<details>
    <summary>💥 <b>ERROR</b> Check if the vertical metrics of a family are similar to the same family hosted on Google Fonts. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/googlefonts.vmetrics.html#"></a></summary>
    <div>

* 💥 **ERROR** <p>'manifest'</p>
 [code: error]

</div>
</details>

## Expected behaviour

Remove the error so gftools qa can generate all the proofs (it stops because of the ERRORS)

## Resources and steps needed to reproduce

You can run fontbakery on https://github.com/googlefonts/Libre-Franklin/tree/master/fonts/variable

**Comment by felipesanches** [comment]
This was fixed by @m4rc1e at #4826 and will be included in the upcoming release (FB v0.13.0-rc1).
