### ISSUE TITLE
Multithreading causes errors in version 0.13.0a0

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fontbakery#4834]
## Observed behavior

Using multiple threads causes errors with the message `Failed with RuntimeError: dictionary changed size during iteration` from the `deepcopy` calls added in version 0.13.0a0. I have seen this error appear in `arabic_high_hamza`, `empty_glyph_on_gid1_for_colrv0`, and `opentype/italic_angle`.

## Expected behavior

All checks should be independent and should not interfere with each other with multiple threads.

## Resources and steps needed to reproduce

```zsh
curl -LO https://github.com/notofonts/duployan/releases/download/NotoSansDuployan-v3.002/NotoSansDuployan-v3.002.zip
unzip NotoSansDuployan-v3.002.zip
python3.11 -m venv venv
. venv/bin/activate
pip install 'fontbakery[notofonts]==0.13a'
fontbakery check-notofonts --jobs 12 NotoSansDuployan/unhinted/otf/NotoSansDuployan-Regular.otf
```

**Comment by Hoolean** [comment]
> Hello! We are seeing this again with v0.13.x (**note:** still a pre-release); could the issue be re-opened to track? :)
>
> In particular, we saw a `RuntimeError: dictionary changed size during iteration` on `TTFont` in:
>
> - `arabic_high_hamza`
> - `empty_glyph_on_gid1_for_colrv0`
>
> The issue will not be in these checks but instead in another that is concurrently mutating an un-deep-copied `TTFont`; are we aware of any new checks in the upcoming release that may be doing so?

_Originally posted by @Hoolean in https://github.com/fonttools/fontbakery/issues/4638#issuecomment-2349539905_

**Comment by Hoolean** [comment]
I've started leafing through the other checks in this profile, and have spotted one that modifies `TTFont` without copying first:

https://github.com/fonttools/fontbakery/blob/4afa3df812f1d8a204647f1917a92df5f40e23f2/Lib/fontbakery/checks/glyphset.py#L405-L410

However, this may not be the same bug, as the error message indicates that a dictionary is causing the issue.

I can put up a PR that adds a copy on Monday, and then if it is still unresolved then we can see if anything else jumps out.

**Comment by dscorbett** [comment]
Another possible problem is:

https://github.com/fonttools/fontbakery/blob/4afa3df812f1d8a204647f1917a92df5f40e23f2/Lib/fontbakery/utils.py#L544-L552

**Comment by Hoolean** [comment]
I've made a draft PR that targets the mutation from our comments (#4835); I will see if I can still reproduce :)

**Comment by Hoolean** [comment]
The PR fixed the error for me locally although, as it's a race condition, I may have just been 'lucky'... Even if not, it's probably still worth us merging to repel future errors.

@dscorbett [The branch is uploaded here](https://github.com/daltonmaag/fontbakery/tree/avoid-ttfont-mutation) if you would like to try it too 🤜🤛

---

I will not have availability to investigate the failing test on the PR for a another day or so; @felipesanches in case you get a spare moment to nudge it forwards, I think the fork is configured to allow you access :)

**Comment by dscorbett** [comment]
I ran a test a few times with 0.13.0a0 and with this branch. This branch seems to fix all the multithreading problems (at least in Python 3.11).
