### ISSUE TITLE
remote_styles is dead

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4837]
The remote_styles condition uses `https://fonts.google.com/download/list?family={}` to get a manifest of filenames and URLs to download the font family, but this URL no longer provides such a list, so anything which calls `remote_styles` crashes with an error:

```
  File "/Users/simon/others-repos/fontbakery/Lib/fontbakery/checks/googlefonts/conditions.py", line 311,
in regular_remote_style
    remote_styles = font.remote_styles
                    ^^^^^^^^^^^^^^^^^^
  File
"/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/functools.p
y", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/others-repos/fontbakery/Lib/fontbakery/checks/googlefonts/conditions.py", line 287,
in remote_styles
    for item in data["manifest"]["fileRefs"]:
                ~~~~^^^^^^^^^^^^
KeyError: 'manifest'
```

Suggest looking at how `gftools.utils.download_family_from_Google_Fonts` works. Although it seems to use the same URL. Um. Don't know.

**Comment by m4rc1e** [comment]
Currently improving remote_styles in #4836

**Comment by simoncozens** [comment]
This is actually #4088 in disguise.
