### ISSUE TITLE
[com.google.fonts/check/whitespace_glyphnames] should accept uniXXXX names

### ISSUE THREAD

**Issue by rimas-kudelis** [fonttools/fontbakery#4851]
I was redirected here from https://github.com/googlefonts/ufo2ft/issues/878.

## Observed behaviour

When production names are enabled, `fontmake` will compile fonts with all glyphs except `.notdef` using the `uniXXXX` name. This includes whitespace glyphs. As a result, Fontbakery warns about "uni0020" not being a proper name. It should not warn about that, since the name is valid per all relevant specs.

## Expected behaviour

No warning should be issued about a glyph named "uni0020".

## Resources and steps needed to reproduce

Compile a font with the `--production-names` argument using fontmake, and validate it against the Google profile.

**Comment by khaledhosny** [comment]
This is a bogus check that should be removed completely.

This code first appeared in #612 (after git blaming a labyrinth of rewrites, moving, splitting, and merging files), with no rationale whatsoever why it cares about glyph names at all (the code being added in this PR was meant to add space and NBSP to fonts that don’t have them). Then code was blindly moved around and one ever stopped to ask why do we have this check in the first place.

**Comment by felipesanches** [comment]
"The Adobe Glyph List (AGL) is a mapping of 4,281 glyph names to one or more Unicode characters. Its purpose is to provide an implementation guideline for consumers of fonts (mainly software applications); it lists a variety of standard names that are given to glyphs that correspond to certain Unicode character sequences. The AGL is maintained by Adobe Systems."

https://en.wikipedia.org/wiki/Adobe_Glyph_List

**Comment by felipesanches** [comment]
The rationale states:
"This check enforces adherence to recommended whitespace (codepoints 0020 and 00A0) glyph names according to the Adobe Glyph List."

**Comment by khaledhosny** [comment]
When the code as first added 1) no mention of AGL at all (and one of the names it checked for isn’t even in AGL) 2) it has no business checking glyph names, and code was copied around blindly then a rationale was retrofitted. 3) The check still rejects AGL-complient names 4) why check for space and NBSP glyph names, what is special about them?

**Comment by felipesanches** [comment]
Sure. It is clear to me that the development history was messy. But now that we do have a check for AGL compliance, wouldn't it be good to fully implement it for the entire AGL spec instead of just the special case of space chars?
And then give it a proper check-id that clearly indicates its purpose (such as 'agl_compliance').

**Comment by rimas-kudelis** [comment]
Funny thing, the commit @khaledhosny pointed to actually accepted `"uni0020"` as a name. The current code does not.
I'll be glad either way, whether this check is removed entirely, or refactored to accept all AGL-compliant glyph names.

**Comment by khaledhosny** [comment]
> But now that we do have a check for AGL compliance, wouldn't it be good to fully implement it for the entire AGL spec instead of just the special case of space chars?

That would be an entirely new check that needs a rationale and to decide what profile to have it in, etc. Glyph names are not something that anyone should depend upon, and the utility of AGL is questionable or usable for very specific and narrow circumstances. So the check here should be dropped, and a new check can be developed if necessary at all.
