### ISSUE TITLE
[opentype/name/italic_names] Wrong proflie

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4858]
This check uses the filename to determine whether the font should have various italic bits set. I don't believe file naming is a matter for the OpenType specification, so this should be under Universal.

**Comment by khaledhosny** [comment]
These file naming convenvtions are very Google Fonts-specific, and we already have many reports where they fail. All these checks belong to googlefonts profile until they are actually made universal (if that can happen at all, there is no standard for naming font files and any thing that depends on file names is by definition not universal).
