### ISSUE TITLE
[unreachable_subsetting] should not flag characters part of Google Fonts Latin core 

### ISSUE THREAD

**Issue by mitradranirban** [fonttools/fontbakery#4862]
## Observed behaviour
The check says 
 The following codepoints supported by the font are not covered by any subsets defined in the font
U+02D8 BREVE: try adding one of: yi, canadian-aboriginal
U+02D9 DOT ABOVE: try adding one of: yi, canadian-aboriginal
U+02DB OGONEK: try adding one of: yi, canadian-aboriginal
U+0302 COMBINING CIRCUMFLEX ACCENT: try adding one of: tifinagh, math, cherokee, coptic
U+0306 COMBINING BREVE: try adding one of: tifinagh, old-permic
U+0307 COMBINING DOT ABOVE: try adding one of: hebrew, old-permic, math, todhri, canadian-aboriginal, tai-le, duployan, coptic, malayalam, syriac, tifinagh
U+030A COMBINING RING ABOVE: try adding one of: duployan, syriac
U+030B COMBINING DOUBLE ACUTE ACCENT: try adding one of: osage, cherokee
U+030C COMBINING CARON: try adding one of: cherokee, tai-le
U+0326 COMBINING COMMA BELOW: try adding math
U+0327 COMBINING CEDILLA: try adding math
U+0328 COMBINING OGONEK: not included in any glyphset definition
U+0331 COMBINING MACRON BELOW: try adding one of: caucasian-albanian, sunuwar, syriac, gothic, thai, tifinagh, cherokee

Or you can add the above codepoints to one of the subsets supported by the font: devanagari, latin, latin-ext
## Expected behaviour

As these charcters are part of GF Latin Core they should not be flagged 
 
## Resources and steps needed to reproduce
font Samaano https://github.com/mitradranirban/samaano-fonts
 FontBakery version  0.12.10
 OS Ubuntu 22.04
 Python version, 3.10.12

**Comment by simoncozens** [comment]
This is not a bug. There are two different concepts here which need to be separated:

* A *glyphset* is set of *glyphs* which designers use to organise the glyphs that they are drawing. GF Latin Core is a glyphset.
* A *subset* is a set of *characters* which the Google Fonts front-ends uses to split the font into various sub fonts for CSS delivery. 

The glyph `circumflexcomb` is in GF Latin Core, so designers should design it. But sadly U+0302 is *not* in the `latin` subset served by the Google Fonts front end. (There are long and complicated discussions about why this is the case. We know it's not ideal.) So a warning that a glyph in the font will not be served by the GF front end is a useful thing to have.
