### ISSUE TITLE
[com.google.fonts/check/vendor_id] review vendor ID warn policy

### ISSUE THREAD

**Issue by rimas-kudelis** [fonttools/fontbakery#4867]
(**NOTE:** Please include the check-id in the issue's title.)

## Observed behaviour

The check in question currently warns when OS/2 `achVendID` is missing or is set to one of the default strings or is set to an unknown value (not in Microsoft's database).

In my opinion, this whole approach of "registering font vendors" in a centralized fashion with Microsoft is very outdated. It originated back when open-source fonts were pretty much nonexistant and when the list consisted of only a handful of vendor tags ([Apple's TrueType Reference Manual](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6OS2.html) lists the original 19). Nowadays, maintaining that registry and relying on it in any way seems to me a rather futile and meaningless excercise, since almost every open-source font project could then be considered as a separate "vendor", and there's nothing in the [vendor list page](https://learn.microsoft.com/en-us/typography/vendors/) that can't be communicated via the `name` table (specifically, `nameID`s 8 and 11).

Also, neither Windows Font Viewer, nor Gnome Fonts, nor even Google Fonts do anything with that field. Are there any popular tools that do?

## Expected behaviour

I suggest that instead of what it does now, the `vendor_id` check should:
- either warn or err out when `achVendorID` is one of the default values: such default value has no value (pun intended) to the user
- warn or err out if `achVendorID` is otherwise unknown: it could be a warning because it's possible that the designer has registered their foundry already, but the registration hasn't propagated to FontBakery yet, but it could as well be an error since that ID is useless in general, but is even more useless while registration hasn't been completed (and FontBakery has new releases quite often, so it's not like a database update will lag a lot).
- allow an empty (unset) value to pass through without a warning: all that such warning achieves is either nothing (if the user ignores it), or more work of very questionable value (if the user gives in to "fixing" it and proceeds with registration of their own vendor tag).

## Resources and steps needed to reproduce

No specific resources or steps are needed, but I'm quite positive that you have some fonts in GF which get a warning from this test.

**Comment by vv-monsalve** [comment]
@davelab6, what do you think?

**Comment by davelab6** [comment]
I was just chatting with @charlesberret and @bramstein about vendorIDs this week as part of their work on the upcoming new https://almanac.httparchive.org/ fonts chapter. 

The 'warn' outcome of the check seems to remain appropriate to me. The highest quality font releases are from vendors that took care to register with Microsoft, and I see no reason not to recommend that high quality libre font releases follow suit. 

Is this outdated? Reminding of a bygone era when there were only 19 'serious' foundries? Sure. Welcome to type design as a profession. :)

**Comment by rimas-kudelis** [comment]
> The highest quality font releases are from vendors that took care to register with Microsoft

Even if this is the case, this doesn't work the other way around: registering with MS does not increase font quality one bit.

**Comment by davelab6** [comment]
This is true. 

But it's a big club, and I like people to be in it ;)

(This is a riff off https://www.youtube.com/watch?v=Nyvxt1svxso)

**Comment by rimas-kudelis** [comment]
Okay, I've already disabled this check for my font. Just had to find out how to do this. :smirk: 

By the way, since Google is rebuilding/subsetting/whatever all fonts on Google Fonts, shouldn't you be replacing all of these tags with `GOOG` anyway? :smile:
