### ISSUE TITLE
[family/control_chars] Not a family check

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4896]
As [mentioned in the review comments](https://github.com/fonttools/fontbakery/pull/2430#discussion_r270565073) this check (in `glyphset.py`) does not need to be a family check; it deals with one font at a time. While I understand the rationale in that discussion that it's nice to have one report per family, this isn't how we treat other similar checks, so this one ends up being inconsistent.

Since we have so many checks which just look at an individual font, I suggest that the [clustering of directory results into a single report](https://github.com/fonttools/fontbakery/issues/2431) is a higher-level operation and should not be done at the check level unless the check really does need to look across fonts in a directory.

In fontspector I'm just going to implement this as an "individual" check called `control_chars` for consistency with other checks.

**Comment by felipesanches** [comment]
Sorry! I quickly renamed the check but I forgot to also change the implementation. I'll do so now.

**Comment by felipesanches** [comment]
done ;-)
