### ISSUE TITLE
[inconsistencies_between_fvar_stat] and [opentype/stat_has_axis_value_tables] do the same thing

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fontbakery#4916]
Both of these checks:

* loop over the `fvar` table's named instances
* loop over the instance's coordinates in axis/value pairs
* find a STAT table design axis entry for the axis
* and check that it has a value entry for the instance's value.

`opentype/stat_has_axis_value_tables` gathers the axis/values from the STAT table first and uses that to compare against the instance values, but otherwise they're identical. `inconsistencies_between_fvar_stat` claims to check "if STAT entries matches fvar and vice versa", but it does not do the "vice versa". They're the same check.

**Comment by felipesanches** [comment]
Would it be acceptable to simply deprecate one of them? Which one?

**Comment by simoncozens** [comment]
Yes, we should deprecate one. The spec says:

> In a variable font, it is strongly recommended that axis value tables be included for every element of typographic subfamily names for all of the named instances defined in the 'fvar' table.

So it's a strong recommendation but not a requirement; so not strictly an OpenType profile check. I suggest we deprecate `opentype/stat_has_axis_value_tables`, because the other one (inconsistencies...) potentially has a wider scope in the future, checking back from the fvar table to the STAT table.
