### ISSUE TITLE
[colorfont_tables] Should not be in universal profile

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fontbakery#4945]
## Observed behaviour

`colorfont_tables` check encode a very specific set of requirements that Google Fonts want but there is nothing universal about it. For example, it FAIL’s fonts that has both `COLR` v0 and `SVG` tables, but that is just a Google Fonts requirement since `COLR` v0 is universally supported by relevant web browsers, however desktop application’s support is a different story and fonts have valid reasons to include both table.

## Expected behaviour

`colorfont_tables` implements a set of Google Fonts requirements and should have remained a Google Fonts check.

## Resources and steps needed to reproduce

https://github.com/aliftype/raqq/releases/tag/v2.00 FAIL’s with this check.

**Comment by felipesanches** [comment]
Thanks for the feedback! I've just moved the check back to the Google Fonts profile.
