### ISSUE TITLE
[epar] time to drop this check

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fontbakery#4947]
## Observed behaviour

Every font in the known universe gets an INFO message that “EPAR table not present in font”.

## Expected behaviour

Every font in the known universe does not get an INFO message that “EPAR table not present in font”.

## Resources and steps needed to reproduce

Every font in the known universe.

**Comment by felipesanches** [comment]
@davelab6, I believe @khaledhosny is correct about this. Since you were the original proponent, I'd like to hear from you.

I'll probably fully deprecate this check at v0.13.0 (very soon!)

**Comment by felipesanches** [comment]
@davelab6 I've deprecate this now.
