### ISSUE TITLE
Write checks for each thing listed in a spreadsheet

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#95]
[This](https://docs.google.com/spreadsheets/d/1HdHpHgmekbc9oa0Hf_EGHZosFZoqgeS5DR8bGER7VJc/edit) is the list; 
- [ ] Col C is out of date - Mikhail made a 2nd tab, but I didn't review which things are implemented, As you look at the test code, please bring col C up to date.
- [ ] write python checks for all tests listed in the lint tool document
- [ ] write python checks for all tests listed in the lint tool spreadsheet
- [ ] https://github.com/xen/fontbakery/issues/69 has a test in it to be brought into the codebase

**Comment by davelab6** [comment]
> Next action is for me to check on status of this

I think that is still the case.

**Comment by felipesanches** [comment]
@davelab6 Should we drop this one as deprecated? Or move it to a future milestone (waiting feedback) ?

**Comment by felipesanches** [comment]
Moving to a future milestone.

**Comment by felipesanches** [comment]
This issue is 5 years old. Is it still relevant, @davelab6 ?

**Comment by simoncozens** [comment]
Seems no real desire for it. ;-)
